[package]
name = "sync-committee-primitives"
version = "0.1.1"
edition = "2021"
authors = ["Polytope Labs"]
publish = false

[dependencies]
hex-literal = { workspace = true }
codec = { workspace = true, features = ["derive"] }
primitive-types = { workspace = true, features = [
    "serde_no_std",
    "impl-codec",
] }
serde = { workspace = true, optional = true, features = ["derive"] }
hex = { workspace = true, default-features = false, features = ["alloc"] }
anyhow = { workspace = true, default-features = false }
serde-hex-utils = { workspace = true, default-features = false }
bls-utils = { workspace = true, default-features = false }

ssz = { workspace = true }
ssz_derive = { workspace = true }
ssz_types = { workspace = true }
tree_hash = { workspace = true, features = ["sha2"] }
tree_hash_derive = { workspace = true }

alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rlp-derive = { workspace = true }


[features]
default = ["std"]
std = [
    "ssz/std",
    "ssz_types/std",
    "tree_hash/std",
    'codec/std',
    "primitive-types/std",
    "anyhow/std",
    "primitive-types/std",
    "serde",
    "serde-hex-utils/std",
    "bls-utils/std",
    "alloy-primitives/std",
    "alloy-primitives/serde",
    "alloy-rlp/std",
]

[dev-dependencies]
serde_json = "1.0.99"
