/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC5679Ext20,
  IERC5679Ext20Interface,
} from "../../../../ERC6160/interfaces/IERC6160Ext20.sol/IERC5679Ext20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC5679Ext20__factory {
  static readonly abi = _abi;
  static createInterface(): IERC5679Ext20Interface {
    return new Interface(_abi) as IERC5679Ext20Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC5679Ext20 {
    return new Contract(address, _abi, runner) as unknown as IERC5679Ext20;
  }
}
