// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_intents
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (unimplemented)
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `(unimplemented)`, CPU: `(unimplemented)`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// (unimplemented)

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::{sp_core::Get, sp_runtime::Weight, *};
use core::marker::PhantomData;

/// Weight functions needed for pallet_intents.
pub trait WeightInfo {
	fn place_bid() -> Weight;
	fn retract_bid() -> Weight;
	fn add_gateway_deployment() -> Weight;
	fn update_gateway_params() -> Weight;
	fn sweep_gateway_dust() -> Weight;
	fn update_oracle_token_decimals() -> Weight;
}

/// Weights for pallet_intents using the Substrate node and recommended hardware.
#[allow(dead_code)]
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Bids (r:1 w:1)
	/// Proof Skipped: Bids (max_values: None, max_size: None, mode: Measured)
	fn place_bid() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3000))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Bids (r:1 w:1)
	/// Proof Skipped: Bids (max_values: None, max_size: None, mode: Measured)
	fn retract_bid() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3000))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Gateways (r:0 w:1)
	/// Proof Skipped: Gateways (max_values: None, max_size: None, mode: Measured)
	fn add_gateway_deployment() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2000))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Gateways (r:1 w:1)
	/// Proof Skipped: Gateways (max_values: None, max_size: None, mode: Measured)
	/// Storage: Nonce (r:1 w:1)
	/// Proof Skipped: Nonce (max_values: Some(1), max_size: None, mode: Measured)
	fn update_gateway_params() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4000))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: Gateways (r:1 w:0)
	/// Proof Skipped: Gateways (max_values: None, max_size: None, mode: Measured)
	/// Storage: Nonce (r:1 w:1)
	/// Proof Skipped: Nonce (max_values: Some(1), max_size: None, mode: Measured)
	fn sweep_gateway_dust() -> Weight {
		Weight::from_parts(70_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3500))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Gateways (r:1 w:0)
	/// Proof Skipped: Gateways (max_values: None, max_size: None, mode: Measured)
	/// Storage: Nonce (r:1 w:1)
	/// Proof Skipped: Nonce (max_values: Some(1), max_size: None, mode: Measured)
	fn update_oracle_token_decimals() -> Weight {
		Weight::from_parts(75_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3500))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn place_bid() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn retract_bid() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn add_gateway_deployment() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn update_gateway_params() -> Weight {
		Weight::from_parts(80_000_000, 0)
	}
	fn sweep_gateway_dust() -> Weight {
		Weight::from_parts(70_000_000, 0)
	}
	fn update_oracle_token_decimals() -> Weight {
		Weight::from_parts(75_000_000, 0)
	}
}
