export const INTENT_GATEWAY_V2_ABI = [
	{
		type: "constructor",
		inputs: [{ name: "admin", type: "address", internalType: "address" }],
		stateMutability: "nonpayable",
	},
	{ type: "receive", stateMutability: "payable" },
	{
		type: "function",
		name: "DOMAIN_SEPARATOR",
		inputs: [],
		outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "SELECT_SOLVER_TYPEHASH",
		inputs: [],
		outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "_destinationProtocolFees",
		inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "_filled",
		inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "_instances",
		inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "_nonce",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "_orders",
		inputs: [
			{ name: "", type: "bytes32", internalType: "bytes32" },
			{ name: "", type: "address", internalType: "address" },
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "_partialFills",
		inputs: [
			{ name: "", type: "bytes32", internalType: "bytes32" },
			{ name: "", type: "bytes32", internalType: "bytes32" },
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "calculateCommitmentSlotHash",
		inputs: [{ name: "commitment", type: "bytes32", internalType: "bytes32" }],
		outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
		stateMutability: "pure",
	},
	{
		type: "function",
		name: "cancelOrder",
		inputs: [
			{
				name: "order",
				type: "tuple",
				internalType: "struct Order",
				components: [
					{ name: "user", type: "bytes32", internalType: "bytes32" },
					{ name: "source", type: "bytes", internalType: "bytes" },
					{ name: "destination", type: "bytes", internalType: "bytes" },
					{ name: "deadline", type: "uint256", internalType: "uint256" },
					{ name: "nonce", type: "uint256", internalType: "uint256" },
					{ name: "fees", type: "uint256", internalType: "uint256" },
					{ name: "session", type: "address", internalType: "address" },
					{
						name: "predispatch",
						type: "tuple",
						internalType: "struct DispatchInfo",
						components: [
							{
								name: "assets",
								type: "tuple[]",
								internalType: "struct TokenInfo[]",
								components: [
									{ name: "token", type: "bytes32", internalType: "bytes32" },
									{ name: "amount", type: "uint256", internalType: "uint256" },
								],
							},
							{ name: "call", type: "bytes", internalType: "bytes" },
						],
					},
					{
						name: "inputs",
						type: "tuple[]",
						internalType: "struct TokenInfo[]",
						components: [
							{ name: "token", type: "bytes32", internalType: "bytes32" },
							{ name: "amount", type: "uint256", internalType: "uint256" },
						],
					},
					{
						name: "output",
						type: "tuple",
						internalType: "struct PaymentInfo",
						components: [
							{ name: "beneficiary", type: "bytes32", internalType: "bytes32" },
							{
								name: "assets",
								type: "tuple[]",
								internalType: "struct TokenInfo[]",
								components: [
									{ name: "token", type: "bytes32", internalType: "bytes32" },
									{ name: "amount", type: "uint256", internalType: "uint256" },
								],
							},
							{ name: "call", type: "bytes", internalType: "bytes" },
						],
					},
				],
			},
			{
				name: "options",
				type: "tuple",
				internalType: "struct CancelOptions",
				components: [
					{ name: "relayerFee", type: "uint256", internalType: "uint256" },
					{ name: "height", type: "uint256", internalType: "uint256" },
				],
			},
		],
		outputs: [],
		stateMutability: "payable",
	},
	{
		type: "function",
		name: "eip712Domain",
		inputs: [],
		outputs: [
			{ name: "fields", type: "bytes1", internalType: "bytes1" },
			{ name: "name", type: "string", internalType: "string" },
			{ name: "version", type: "string", internalType: "string" },
			{ name: "chainId", type: "uint256", internalType: "uint256" },
			{ name: "verifyingContract", type: "address", internalType: "address" },
			{ name: "salt", type: "bytes32", internalType: "bytes32" },
			{ name: "extensions", type: "uint256[]", internalType: "uint256[]" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "fillOrder",
		inputs: [
			{
				name: "order",
				type: "tuple",
				internalType: "struct Order",
				components: [
					{ name: "user", type: "bytes32", internalType: "bytes32" },
					{ name: "source", type: "bytes", internalType: "bytes" },
					{ name: "destination", type: "bytes", internalType: "bytes" },
					{ name: "deadline", type: "uint256", internalType: "uint256" },
					{ name: "nonce", type: "uint256", internalType: "uint256" },
					{ name: "fees", type: "uint256", internalType: "uint256" },
					{ name: "session", type: "address", internalType: "address" },
					{
						name: "predispatch",
						type: "tuple",
						internalType: "struct DispatchInfo",
						components: [
							{
								name: "assets",
								type: "tuple[]",
								internalType: "struct TokenInfo[]",
								components: [
									{ name: "token", type: "bytes32", internalType: "bytes32" },
									{ name: "amount", type: "uint256", internalType: "uint256" },
								],
							},
							{ name: "call", type: "bytes", internalType: "bytes" },
						],
					},
					{
						name: "inputs",
						type: "tuple[]",
						internalType: "struct TokenInfo[]",
						components: [
							{ name: "token", type: "bytes32", internalType: "bytes32" },
							{ name: "amount", type: "uint256", internalType: "uint256" },
						],
					},
					{
						name: "output",
						type: "tuple",
						internalType: "struct PaymentInfo",
						components: [
							{ name: "beneficiary", type: "bytes32", internalType: "bytes32" },
							{
								name: "assets",
								type: "tuple[]",
								internalType: "struct TokenInfo[]",
								components: [
									{ name: "token", type: "bytes32", internalType: "bytes32" },
									{ name: "amount", type: "uint256", internalType: "uint256" },
								],
							},
							{ name: "call", type: "bytes", internalType: "bytes" },
						],
					},
				],
			},
			{
				name: "options",
				type: "tuple",
				internalType: "struct FillOptions",
				components: [
					{ name: "relayerFee", type: "uint256", internalType: "uint256" },
					{ name: "nativeDispatchFee", type: "uint256", internalType: "uint256" },
					{
						name: "outputs",
						type: "tuple[]",
						internalType: "struct TokenInfo[]",
						components: [
							{ name: "token", type: "bytes32", internalType: "bytes32" },
							{ name: "amount", type: "uint256", internalType: "uint256" },
						],
					},
				],
			},
		],
		outputs: [],
		stateMutability: "payable",
	},
	{
		type: "function",
		name: "host",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "instance",
		inputs: [{ name: "stateMachineId", type: "bytes", internalType: "bytes" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "onAccept",
		inputs: [
			{
				name: "incoming",
				type: "tuple",
				internalType: "struct IncomingPostRequest",
				components: [
					{
						name: "request",
						type: "tuple",
						internalType: "struct PostRequest",
						components: [
							{ name: "source", type: "bytes", internalType: "bytes" },
							{ name: "dest", type: "bytes", internalType: "bytes" },
							{ name: "nonce", type: "uint64", internalType: "uint64" },
							{ name: "from", type: "bytes", internalType: "bytes" },
							{ name: "to", type: "bytes", internalType: "bytes" },
							{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
							{ name: "body", type: "bytes", internalType: "bytes" },
						],
					},
					{ name: "relayer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "onGetResponse",
		inputs: [
			{
				name: "incoming",
				type: "tuple",
				internalType: "struct IncomingGetResponse",
				components: [
					{
						name: "response",
						type: "tuple",
						internalType: "struct GetResponse",
						components: [
							{
								name: "request",
								type: "tuple",
								internalType: "struct GetRequest",
								components: [
									{ name: "source", type: "bytes", internalType: "bytes" },
									{ name: "dest", type: "bytes", internalType: "bytes" },
									{ name: "nonce", type: "uint64", internalType: "uint64" },
									{ name: "from", type: "address", internalType: "address" },
									{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
									{ name: "keys", type: "bytes[]", internalType: "bytes[]" },
									{ name: "height", type: "uint64", internalType: "uint64" },
									{ name: "context", type: "bytes", internalType: "bytes" },
								],
							},
							{
								name: "values",
								type: "tuple[]",
								internalType: "struct StorageValue[]",
								components: [
									{ name: "key", type: "bytes", internalType: "bytes" },
									{ name: "value", type: "bytes", internalType: "bytes" },
								],
							},
						],
					},
					{ name: "relayer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "onGetTimeout",
		inputs: [
			{
				name: "",
				type: "tuple",
				internalType: "struct GetRequest",
				components: [
					{ name: "source", type: "bytes", internalType: "bytes" },
					{ name: "dest", type: "bytes", internalType: "bytes" },
					{ name: "nonce", type: "uint64", internalType: "uint64" },
					{ name: "from", type: "address", internalType: "address" },
					{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
					{ name: "keys", type: "bytes[]", internalType: "bytes[]" },
					{ name: "height", type: "uint64", internalType: "uint64" },
					{ name: "context", type: "bytes", internalType: "bytes" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "onPostRequestTimeout",
		inputs: [
			{
				name: "",
				type: "tuple",
				internalType: "struct PostRequest",
				components: [
					{ name: "source", type: "bytes", internalType: "bytes" },
					{ name: "dest", type: "bytes", internalType: "bytes" },
					{ name: "nonce", type: "uint64", internalType: "uint64" },
					{ name: "from", type: "bytes", internalType: "bytes" },
					{ name: "to", type: "bytes", internalType: "bytes" },
					{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
					{ name: "body", type: "bytes", internalType: "bytes" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "onPostResponse",
		inputs: [
			{
				name: "",
				type: "tuple",
				internalType: "struct IncomingPostResponse",
				components: [
					{
						name: "response",
						type: "tuple",
						internalType: "struct PostResponse",
						components: [
							{
								name: "request",
								type: "tuple",
								internalType: "struct PostRequest",
								components: [
									{ name: "source", type: "bytes", internalType: "bytes" },
									{ name: "dest", type: "bytes", internalType: "bytes" },
									{ name: "nonce", type: "uint64", internalType: "uint64" },
									{ name: "from", type: "bytes", internalType: "bytes" },
									{ name: "to", type: "bytes", internalType: "bytes" },
									{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
									{ name: "body", type: "bytes", internalType: "bytes" },
								],
							},
							{ name: "response", type: "bytes", internalType: "bytes" },
							{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
						],
					},
					{ name: "relayer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "onPostResponseTimeout",
		inputs: [
			{
				name: "",
				type: "tuple",
				internalType: "struct PostResponse",
				components: [
					{
						name: "request",
						type: "tuple",
						internalType: "struct PostRequest",
						components: [
							{ name: "source", type: "bytes", internalType: "bytes" },
							{ name: "dest", type: "bytes", internalType: "bytes" },
							{ name: "nonce", type: "uint64", internalType: "uint64" },
							{ name: "from", type: "bytes", internalType: "bytes" },
							{ name: "to", type: "bytes", internalType: "bytes" },
							{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
							{ name: "body", type: "bytes", internalType: "bytes" },
						],
					},
					{ name: "response", type: "bytes", internalType: "bytes" },
					{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "params",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "tuple",
				internalType: "struct Params",
				components: [
					{ name: "host", type: "address", internalType: "address" },
					{ name: "dispatcher", type: "address", internalType: "address" },
					{ name: "solverSelection", type: "bool", internalType: "bool" },
					{ name: "surplusShareBps", type: "uint256", internalType: "uint256" },
					{ name: "protocolFeeBps", type: "uint256", internalType: "uint256" },
					{ name: "priceOracle", type: "address", internalType: "address" },
				],
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "placeOrder",
		inputs: [
			{
				name: "order",
				type: "tuple",
				internalType: "struct Order",
				components: [
					{ name: "user", type: "bytes32", internalType: "bytes32" },
					{ name: "source", type: "bytes", internalType: "bytes" },
					{ name: "destination", type: "bytes", internalType: "bytes" },
					{ name: "deadline", type: "uint256", internalType: "uint256" },
					{ name: "nonce", type: "uint256", internalType: "uint256" },
					{ name: "fees", type: "uint256", internalType: "uint256" },
					{ name: "session", type: "address", internalType: "address" },
					{
						name: "predispatch",
						type: "tuple",
						internalType: "struct DispatchInfo",
						components: [
							{
								name: "assets",
								type: "tuple[]",
								internalType: "struct TokenInfo[]",
								components: [
									{ name: "token", type: "bytes32", internalType: "bytes32" },
									{ name: "amount", type: "uint256", internalType: "uint256" },
								],
							},
							{ name: "call", type: "bytes", internalType: "bytes" },
						],
					},
					{
						name: "inputs",
						type: "tuple[]",
						internalType: "struct TokenInfo[]",
						components: [
							{ name: "token", type: "bytes32", internalType: "bytes32" },
							{ name: "amount", type: "uint256", internalType: "uint256" },
						],
					},
					{
						name: "output",
						type: "tuple",
						internalType: "struct PaymentInfo",
						components: [
							{ name: "beneficiary", type: "bytes32", internalType: "bytes32" },
							{
								name: "assets",
								type: "tuple[]",
								internalType: "struct TokenInfo[]",
								components: [
									{ name: "token", type: "bytes32", internalType: "bytes32" },
									{ name: "amount", type: "uint256", internalType: "uint256" },
								],
							},
							{ name: "call", type: "bytes", internalType: "bytes" },
						],
					},
				],
			},
			{ name: "graffiti", type: "bytes32", internalType: "bytes32" },
		],
		outputs: [],
		stateMutability: "payable",
	},
	{
		type: "function",
		name: "quote",
		inputs: [
			{
				name: "request",
				type: "tuple",
				internalType: "struct DispatchPost",
				components: [
					{ name: "dest", type: "bytes", internalType: "bytes" },
					{ name: "to", type: "bytes", internalType: "bytes" },
					{ name: "body", type: "bytes", internalType: "bytes" },
					{ name: "timeout", type: "uint64", internalType: "uint64" },
					{ name: "fee", type: "uint256", internalType: "uint256" },
					{ name: "payer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "quote",
		inputs: [
			{
				name: "request",
				type: "tuple",
				internalType: "struct DispatchGet",
				components: [
					{ name: "dest", type: "bytes", internalType: "bytes" },
					{ name: "height", type: "uint64", internalType: "uint64" },
					{ name: "keys", type: "bytes[]", internalType: "bytes[]" },
					{ name: "timeout", type: "uint64", internalType: "uint64" },
					{ name: "fee", type: "uint256", internalType: "uint256" },
					{ name: "context", type: "bytes", internalType: "bytes" },
				],
			},
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "quote",
		inputs: [
			{
				name: "response",
				type: "tuple",
				internalType: "struct DispatchPostResponse",
				components: [
					{
						name: "request",
						type: "tuple",
						internalType: "struct PostRequest",
						components: [
							{ name: "source", type: "bytes", internalType: "bytes" },
							{ name: "dest", type: "bytes", internalType: "bytes" },
							{ name: "nonce", type: "uint64", internalType: "uint64" },
							{ name: "from", type: "bytes", internalType: "bytes" },
							{ name: "to", type: "bytes", internalType: "bytes" },
							{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
							{ name: "body", type: "bytes", internalType: "bytes" },
						],
					},
					{ name: "response", type: "bytes", internalType: "bytes" },
					{ name: "timeout", type: "uint64", internalType: "uint64" },
					{ name: "fee", type: "uint256", internalType: "uint256" },
					{ name: "payer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "quoteNative",
		inputs: [
			{
				name: "request",
				type: "tuple",
				internalType: "struct DispatchPost",
				components: [
					{ name: "dest", type: "bytes", internalType: "bytes" },
					{ name: "to", type: "bytes", internalType: "bytes" },
					{ name: "body", type: "bytes", internalType: "bytes" },
					{ name: "timeout", type: "uint64", internalType: "uint64" },
					{ name: "fee", type: "uint256", internalType: "uint256" },
					{ name: "payer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "quoteNative",
		inputs: [
			{
				name: "request",
				type: "tuple",
				internalType: "struct DispatchPostResponse",
				components: [
					{
						name: "request",
						type: "tuple",
						internalType: "struct PostRequest",
						components: [
							{ name: "source", type: "bytes", internalType: "bytes" },
							{ name: "dest", type: "bytes", internalType: "bytes" },
							{ name: "nonce", type: "uint64", internalType: "uint64" },
							{ name: "from", type: "bytes", internalType: "bytes" },
							{ name: "to", type: "bytes", internalType: "bytes" },
							{ name: "timeoutTimestamp", type: "uint64", internalType: "uint64" },
							{ name: "body", type: "bytes", internalType: "bytes" },
						],
					},
					{ name: "response", type: "bytes", internalType: "bytes" },
					{ name: "timeout", type: "uint64", internalType: "uint64" },
					{ name: "fee", type: "uint256", internalType: "uint256" },
					{ name: "payer", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "quoteNative",
		inputs: [
			{
				name: "request",
				type: "tuple",
				internalType: "struct DispatchGet",
				components: [
					{ name: "dest", type: "bytes", internalType: "bytes" },
					{ name: "height", type: "uint64", internalType: "uint64" },
					{ name: "keys", type: "bytes[]", internalType: "bytes[]" },
					{ name: "timeout", type: "uint64", internalType: "uint64" },
					{ name: "fee", type: "uint256", internalType: "uint256" },
					{ name: "context", type: "bytes", internalType: "bytes" },
				],
			},
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "select",
		inputs: [
			{
				name: "options",
				type: "tuple",
				internalType: "struct SelectOptions",
				components: [
					{ name: "commitment", type: "bytes32", internalType: "bytes32" },
					{ name: "solver", type: "address", internalType: "address" },
					{ name: "signature", type: "bytes", internalType: "bytes" },
				],
			},
		],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setParams",
		inputs: [
			{
				name: "p",
				type: "tuple",
				internalType: "struct Params",
				components: [
					{ name: "host", type: "address", internalType: "address" },
					{ name: "dispatcher", type: "address", internalType: "address" },
					{ name: "solverSelection", type: "bool", internalType: "bool" },
					{ name: "surplusShareBps", type: "uint256", internalType: "uint256" },
					{ name: "protocolFeeBps", type: "uint256", internalType: "uint256" },
					{ name: "priceOracle", type: "address", internalType: "address" },
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "DestinationProtocolFeeUpdated",
		inputs: [
			{ name: "stateMachineId", type: "bytes32", indexed: true, internalType: "bytes32" },
			{ name: "feeBps", type: "uint256", indexed: false, internalType: "uint256" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "DustCollected",
		inputs: [
			{ name: "token", type: "address", indexed: false, internalType: "address" },
			{ name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "DustSwept",
		inputs: [
			{ name: "token", type: "address", indexed: false, internalType: "address" },
			{ name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
			{ name: "beneficiary", type: "address", indexed: false, internalType: "address" },
		],
		anonymous: false,
	},
	{ type: "event", name: "EIP712DomainChanged", inputs: [], anonymous: false },
	{
		type: "event",
		name: "EscrowRefunded",
		inputs: [{ name: "commitment", type: "bytes32", indexed: true, internalType: "bytes32" }],
		anonymous: false,
	},
	{
		type: "event",
		name: "EscrowReleased",
		inputs: [{ name: "commitment", type: "bytes32", indexed: true, internalType: "bytes32" }],
		anonymous: false,
	},
	{
		type: "event",
		name: "NewDeploymentAdded",
		inputs: [
			{ name: "stateMachineId", type: "bytes", indexed: false, internalType: "bytes" },
			{ name: "gateway", type: "address", indexed: false, internalType: "address" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "OrderFilled",
		inputs: [
			{ name: "commitment", type: "bytes32", indexed: true, internalType: "bytes32" },
			{ name: "filler", type: "address", indexed: false, internalType: "address" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "OrderPlaced",
		inputs: [
			{ name: "user", type: "bytes32", indexed: false, internalType: "bytes32" },
			{ name: "source", type: "bytes", indexed: false, internalType: "bytes" },
			{ name: "destination", type: "bytes", indexed: false, internalType: "bytes" },
			{ name: "deadline", type: "uint256", indexed: false, internalType: "uint256" },
			{ name: "nonce", type: "uint256", indexed: false, internalType: "uint256" },
			{ name: "fees", type: "uint256", indexed: false, internalType: "uint256" },
			{ name: "session", type: "address", indexed: false, internalType: "address" },
			{ name: "beneficiary", type: "bytes32", indexed: false, internalType: "bytes32" },
			{
				name: "predispatch",
				type: "tuple[]",
				indexed: false,
				internalType: "struct TokenInfo[]",
				components: [
					{ name: "token", type: "bytes32", internalType: "bytes32" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
			{
				name: "inputs",
				type: "tuple[]",
				indexed: false,
				internalType: "struct TokenInfo[]",
				components: [
					{ name: "token", type: "bytes32", internalType: "bytes32" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
			{
				name: "outputs",
				type: "tuple[]",
				indexed: false,
				internalType: "struct TokenInfo[]",
				components: [
					{ name: "token", type: "bytes32", internalType: "bytes32" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ParamsUpdated",
		inputs: [
			{
				name: "previous",
				type: "tuple",
				indexed: false,
				internalType: "struct Params",
				components: [
					{ name: "host", type: "address", internalType: "address" },
					{ name: "dispatcher", type: "address", internalType: "address" },
					{ name: "solverSelection", type: "bool", internalType: "bool" },
					{ name: "surplusShareBps", type: "uint256", internalType: "uint256" },
					{ name: "protocolFeeBps", type: "uint256", internalType: "uint256" },
					{ name: "priceOracle", type: "address", internalType: "address" },
				],
			},
			{
				name: "current",
				type: "tuple",
				indexed: false,
				internalType: "struct Params",
				components: [
					{ name: "host", type: "address", internalType: "address" },
					{ name: "dispatcher", type: "address", internalType: "address" },
					{ name: "solverSelection", type: "bool", internalType: "bool" },
					{ name: "surplusShareBps", type: "uint256", internalType: "uint256" },
					{ name: "protocolFeeBps", type: "uint256", internalType: "uint256" },
					{ name: "priceOracle", type: "address", internalType: "address" },
				],
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "PartialFill",
		inputs: [
			{ name: "commitment", type: "bytes32", indexed: true, internalType: "bytes32" },
			{ name: "filler", type: "address", indexed: false, internalType: "address" },
			{
				name: "outputs",
				type: "tuple[]",
				indexed: false,
				internalType: "struct TokenInfo[]",
				components: [
					{ name: "token", type: "bytes32", internalType: "bytes32" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
			{
				name: "inputs",
				type: "tuple[]",
				indexed: false,
				internalType: "struct TokenInfo[]",
				components: [
					{ name: "token", type: "bytes32", internalType: "bytes32" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
		],
		anonymous: false,
	},
	{ type: "error", name: "Cancelled", inputs: [] },
	{ type: "error", name: "ECDSAInvalidSignature", inputs: [] },
	{
		type: "error",
		name: "ECDSAInvalidSignatureLength",
		inputs: [{ name: "length", type: "uint256", internalType: "uint256" }],
	},
	{
		type: "error",
		name: "ECDSAInvalidSignatureS",
		inputs: [{ name: "s", type: "bytes32", internalType: "bytes32" }],
	},
	{ type: "error", name: "Expired", inputs: [] },
	{ type: "error", name: "Filled", inputs: [] },
	{ type: "error", name: "InsufficientNativeToken", inputs: [] },
	{ type: "error", name: "InvalidInput", inputs: [] },
	{ type: "error", name: "InvalidShortString", inputs: [] },
	{ type: "error", name: "NotExpired", inputs: [] },
	{
		type: "error",
		name: "SafeCastOverflowedUintDowncast",
		inputs: [
			{ name: "bits", type: "uint8", internalType: "uint8" },
			{ name: "value", type: "uint256", internalType: "uint256" },
		],
	},
	{
		type: "error",
		name: "SafeERC20FailedOperation",
		inputs: [{ name: "token", type: "address", internalType: "address" }],
	},
	{ type: "error", name: "StringTooLong", inputs: [{ name: "str", type: "string", internalType: "string" }] },
	{ type: "error", name: "Unauthorized", inputs: [] },
	{ type: "error", name: "UnauthorizedCall", inputs: [] },
	{ type: "error", name: "UnexpectedCall", inputs: [] },
	{ type: "error", name: "UnknownOrder", inputs: [] },
	{ type: "error", name: "WrongChain", inputs: [] },
] as const
