services:
    subquery-node-simnode:
        image: subquerynetwork/subql-node-substrate:v5.9.1
        restart: unless-stopped
        network_mode: host
        volumes:
            - ../src/configs:/app
            - ../dist:/app/dist
        command:
            - -f=/app/hyperbridge-simnode.yaml
            - --db-schema=simnode_test
            - --workers=1
            - --batch-size=5
            - --unsafe
            - --log-level=debug
            - --block-confirmations=0
            - --store-cache-async=false
            - --store-cache-threshold=1
            - --skipTransactions
        environment:
            DB_USER: postgres
            DB_PASS: postgres
            DB_DATABASE: indexer
            DB_HOST: 127.0.0.1
            DB_PORT: 5433

    graphql-engine-simnode:
        image: polytopelabs/omnihedron:latest
        restart: unless-stopped
        network_mode: host
        environment:
            DB_USER: postgres
            DB_PASS: postgres
            DB_DATABASE: indexer
            DB_HOST: 127.0.0.1
            DB_PORT: 5433
        command:
            - --name=simnode_test
            - --playground
            - --query-timeout=0
            - --port=3101
