[package]
name = "tempo-verifier"
version = "0.1.0"
edition = "2021"
description = "Verifier for Tempo's commonware simplex consensus proofs"
authors = ["Polytope Labs <hello@polytope.technology>"]
publish = false

[dependencies]
alloy-rlp = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp-derive = { workspace = true }
primitive-types = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
ismp = { workspace = true, default-features = false }
geth-primitives = { workspace = true, default-features = false }
bls = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-bls12-381 = { workspace = true }
sha2 = { version = "0.10", default-features = false }

[dev-dependencies]
json = { workspace = true, features = ["std"] }
hex = { version = "0.4.3", features = ["std"] }
ethabi = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "ismp/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "primitive-types/std",
    "bls/std",
    "ark-ec/std",
    "ark-ff/std",
    "ark-bls12-381/std",
    "sha2/std",
    "geth-primitives/std",
]
