/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc6160Ext20Sol from "./IERC6160Ext20.sol";
export type { ierc6160Ext20Sol };
import type * as iercAclCoreSol from "./IERCAclCore.sol";
export type { iercAclCoreSol };
