[package]
name = "sync-committee-verifier"
version = "0.1.1"
edition = "2021"
authors = ["Polytope Labs"]
publish = false

[dependencies]
sync-committee-primitives = { workspace = true, default-features = false }
ismp = { workspace = true, default-features = false }
primitive-types = { workspace = true, default-features = false }
log = { workspace = true, default-features = false }
anyhow = { workspace = true, default-features = false }
thiserror = { workspace = true }
ssz = { workspace = true, features = ["scale"] }
ssz_types = { workspace = true, features = ["scale"] }
tree_hash = { workspace = true, features = ["sha2"] }
bls = { workspace = true }
ark-ec = { workspace = true }

[features]
default = ["std"]
std = [
    "ssz/std",
    "ssz_types/std",
    "tree_hash/std",
    "log/std",
    "sync-committee-primitives/std",
    "primitive-types/std",
    "log/std",
    "anyhow/std",
    "thiserror/std",
    "ismp/std",
    "bls/std",
    "ark-ec/std",
]

[dev-dependencies]
hex = "0.4.3"
hex-literal = { workspace = true, default-features = true }
