/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC5679Ext20__factory } from "./IERC5679Ext20__factory";
export { IERC6160Ext20__factory } from "./IERC6160Ext20__factory";
