import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { OPTIMISM, BASE } from '../src/constants';

interface OpStackChain {
	name: string;
	chainId: number;
	identifier: string;
	superchainLevel: number;
}

function generateL2ChainsFile() {
	console.log('Generating OP Stack L2 chains from local file...');

	try {
		const __dirname = path.dirname(fileURLToPath(import.meta.url));

		const jsonPath = path.resolve(__dirname, '../src/configs/opstack-chains.json');
		const outputPath = path.resolve(__dirname, '../src/utils/l2-state-machine.helper.ts');

		const chainList: OpStackChain[] = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));

		const hardcodedL2s = [OPTIMISM.mainnet, BASE.mainnet];

		const fetchedL2s = chainList
			.filter(chain => chain.identifier.startsWith('mainnet/'))
			.map(chain => `EVM-${chain.chainId}`);

		const combinedL2s = [...hardcodedL2s, ...fetchedL2s];
		const uniqueL2s = [...new Set(combinedL2s)];

		const fileContent = `
// THIS FILE IS AUTO-GENERATED BY 'scripts/generate-l2-chains.ts'. DO NOT EDIT.

export const GET_ETHEREUM_L2_STATE_MACHINES = (): string[] => {
    return ${JSON.stringify(uniqueL2s.sort(), null, 8)};
};
        `;

		fs.writeFileSync(outputPath, fileContent.trim());
		console.log(`Successfully generated ${uniqueL2s.length} unique L2 chains to ${outputPath}`);
	} catch (error) {
		console.error('Error generating L2 chains file:', error);
		process.exit(1);
	}
}

generateL2ChainsFile();