// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_intents_coprocessor`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `polytope-labs`, CPU: `AMD Ryzen Threadripper PRO 5995WX 64-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=pallet_intents_coprocessor
// --extrinsic=*
// --steps=50
// --repeat=20
// --unsafe-overwrite-results
// --genesis-builder-preset=development
// --template=./scripts/template.hbs
// --genesis-builder=runtime
// --runtime=./target/release/wbuild/gargantua-runtime/gargantua_runtime.compact.wasm
// --output
// parachain/runtimes/gargantua/src/weights/pallet_intents_coprocessor.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_intents_coprocessor`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_intents_coprocessor::WeightInfo for WeightInfo<T> {
	/// Storage: `IntentsCoprocessor::Bids` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Bids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::StorageDepositFee` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::StorageDepositFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn place_bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3574`
		// Minimum execution time: 39_334_000 picoseconds.
		Weight::from_parts(40_928_000, 0)
			.saturating_add(Weight::from_parts(0, 3574))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Bids` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Bids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn retract_bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `3712`
		// Minimum execution time: 38_442_000 picoseconds.
		Weight::from_parts(39_195_000, 0)
			.saturating_add(Weight::from_parts(0, 3712))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:2 w:1)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_deployment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `113`
		//  Estimated: `6053`
		// Minimum execution time: 22_392_000 picoseconds.
		Weight::from_parts(22_934_000, 0)
			.saturating_add(Weight::from_parts(0, 6053))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731fe78f389a61a92311a0a767b480` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731fe78f389a61a92311a0a767b480` (r:1 w:1)
	fn update_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `700`
		//  Estimated: `4165`
		// Minimum execution time: 73_059_000 picoseconds.
		Weight::from_parts(73_890_000, 0)
			.saturating_add(Weight::from_parts(0, 4165))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e7e2297e9ec6ac3afe12f8f523ba` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e7e2297e9ec6ac3afe12f8f523ba` (r:1 w:1)
	fn sweep_dust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `700`
		//  Estimated: `4165`
		// Minimum execution time: 64_562_000 picoseconds.
		Weight::from_parts(65_995_000, 0)
			.saturating_add(Weight::from_parts(0, 4165))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473dca7a0a9e3ad5485a922b1f11f43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473dca7a0a9e3ad5485a922b1f11f43` (r:1 w:1)
	fn update_token_decimals() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `700`
		//  Estimated: `4165`
		// Minimum execution time: 69_372_000 picoseconds.
		Weight::from_parts(70_073_000, 0)
			.saturating_add(Weight::from_parts(0, 4165))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::StorageDepositFee` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::StorageDepositFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_storage_deposit_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_296_000 picoseconds.
		Weight::from_parts(8_607_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::PriceDepositAmount` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::PriceDepositAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::PriceDeposits` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::PriceDeposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::PricesClearedThisWindow` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::PricesClearedThisWindow` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::Prices` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Prices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::CounterForPrices` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::CounterForPrices` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn submit_pair_price(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3665`
		// Minimum execution time: 58_340_000 picoseconds.
		Weight::from_parts(65_029_669, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			// Standard Error: 1_597
			.saturating_add(Weight::from_parts(21_027, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::PriceWindowDurationValue` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::PriceWindowDurationValue` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_price_window_duration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_086_000 picoseconds.
		Weight::from_parts(8_576_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::PriceDepositAmount` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::PriceDepositAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_price_deposit_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_255_000 picoseconds.
		Weight::from_parts(8_446_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::PriceDepositLockDuration` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::PriceDepositLockDuration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_price_deposit_lock_duration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_305_000 picoseconds.
		Weight::from_parts(8_626_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::PriceDeposits` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::PriceDeposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn withdraw_price_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `405`
		//  Estimated: `3870`
		// Minimum execution time: 38_613_000 picoseconds.
		Weight::from_parts(39_174_000, 0)
			.saturating_add(Weight::from_parts(0, 3870))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
