// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_outbound_proofs`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `polytope-labs`, CPU: `AMD Ryzen Threadripper PRO 5995WX 64-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=pallet_outbound_proofs
// --extrinsic=*
// --steps=50
// --repeat=20
// --unsafe-overwrite-results
// --genesis-builder-preset=development
// --template=./scripts/template.hbs
// --genesis-builder=runtime
// --runtime=./target/release/wbuild/gargantua-runtime/gargantua_runtime.compact.wasm
// --output
// parachain/runtimes/gargantua/src/weights/pallet_outbound_proofs.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_outbound_proofs`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_outbound_proofs::WeightInfo for WeightInfo<T> {
	/// Storage: `Ismp::ConsensusStates` (r:1 w:1)
	/// Proof: `Ismp::ConsensusStates` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OutboundProofs::Sp1VkeyHash` (r:1 w:0)
	/// Proof: `OutboundProofs::Sp1VkeyHash` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `OutboundProofs::RecentProofs` (r:1 w:1)
	/// Proof: `OutboundProofs::RecentProofs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OutboundProofs::ProofReward` (r:1 w:0)
	/// Proof: `OutboundProofs::ProofReward` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `547`
		//  Estimated: `4012`
		// Minimum execution time: 669_751_633_000 picoseconds.
		Weight::from_parts(694_774_527_000, 0)
			.saturating_add(Weight::from_parts(0, 4012))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OutboundProofs::ProofReward` (r:0 w:1)
	/// Proof: `OutboundProofs::ProofReward` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_proof_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_696_000 picoseconds.
		Weight::from_parts(9_027_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `OutboundProofs::Sp1VkeyHash` (r:0 w:1)
	/// Proof: `OutboundProofs::Sp1VkeyHash` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_sp1_vkey_hash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_779_000 picoseconds.
		Weight::from_parts(5_490_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
