
//! Autogenerated weights for `pallet_beefy_apk_digest`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-18, STEPS: `2`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `polytope-labs`, CPU: `AMD Ryzen Threadripper PRO 5995WX 64-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/gargantua-runtime/gargantua_runtime.compact.compressed.wasm
// --pallet
// pallet_beefy_apk_digest
// --extrinsic
// commit
// --steps
// 2
// --repeat
// 20
// --output
// /tmp/apk_digest_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_beefy_apk_digest`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_beefy_apk_digest::WeightInfo for WeightInfo<T> {
	fn commit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 584_718_741_000 picoseconds.
		Weight::from_parts(587_530_204_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
