// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_beefy_consensus_proofs`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `polytope-labs`, CPU: `AMD Ryzen Threadripper PRO 5995WX 64-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=pallet_beefy_consensus_proofs
// --extrinsic=*
// --steps=50
// --repeat=20
// --unsafe-overwrite-results
// --genesis-builder-preset=development
// --template=./scripts/template.hbs
// --genesis-builder=runtime
// --runtime=./target/release/wbuild/gargantua-runtime/gargantua_runtime.compact.wasm
// --output
// parachain/runtimes/gargantua/src/weights/pallet_beefy_consensus_proofs.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_beefy_consensus_proofs`.
///
/// `submit_proof` is benchmarked through the uncle path: the SP1 fixture's parachain
/// header carries `para_id = 3367` which doesn't match Gargantua's tracked `para_id`
/// (4009), so `verify_and_apply` runs the SP1 verifier successfully but stores no
/// commitments and bails as `StaleProof`. Dispatch falls through to `settle_uncle_proof`
/// which runs `verify_sp1_consensus` a second time against a pre-seeded snapshot. This
/// gives a conservative weight covering both SP1 verifications plus the uncle storage
/// writes, which also bounds the first-proof path. See `benchmarking.rs::submit_proof`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_beefy_consensus_proofs::WeightInfo for WeightInfo<T> {
	/// Storage: `Ismp::ConsensusStates` (r:1 w:1)
	/// Proof: `Ismp::ConsensusStates` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::LatestStateMachineHeight` (r:1 w:0)
	/// Proof: `Ismp::LatestStateMachineHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::ConsensusStateClient` (r:1 w:0)
	/// Proof: `Ismp::ConsensusStateClient` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::FrozenConsensusClients` (r:1 w:0)
	/// Proof: `Ismp::FrozenConsensusClients` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::UnbondingPeriod` (r:1 w:0)
	/// Proof: `Ismp::UnbondingPeriod` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::ConsensusClientUpdateTime` (r:1 w:1)
	/// Proof: `Ismp::ConsensusClientUpdateTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BeefyConsensusProofs::Sp1VkeyHash` (r:1 w:0)
	/// Proof: `BeefyConsensusProofs::Sp1VkeyHash` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BeefyConsensusProofs::ProofContext` (r:1 w:0)
	/// Proof: `BeefyConsensusProofs::ProofContext` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BeefyConsensusProofs::ProverCount` (r:1 w:1)
	/// Proof: `BeefyConsensusProofs::ProverCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BeefyConsensusProofs::AcceptedProofHashes` (r:1 w:1)
	/// Proof: `BeefyConsensusProofs::AcceptedProofHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BeefyConsensusProofs::ProofReward` (r:1 w:0)
	/// Proof: `BeefyConsensusProofs::ProofReward` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `952`
		//  Estimated: `4417`
		// Minimum execution time: 1_414_974_938_000 picoseconds.
		Weight::from_parts(2_027_477_780_000, 0)
			.saturating_add(Weight::from_parts(0, 4417))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `BeefyConsensusProofs::ProofReward` (r:0 w:1)
	/// Proof: `BeefyConsensusProofs::ProofReward` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_proof_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 33_634_000 picoseconds.
		Weight::from_parts(56_086_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `BeefyConsensusProofs::Sp1VkeyHash` (r:0 w:1)
	/// Proof: `BeefyConsensusProofs::Sp1VkeyHash` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_sp1_vkey_hash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 19_006_000 picoseconds.
		Weight::from_parts(39_275_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `BeefyConsensusProofs::RewardCurve` (r:0 w:1)
	/// Proof: `BeefyConsensusProofs::RewardCurve` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_reward_curve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 39_685_000 picoseconds.
		Weight::from_parts(74_651_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn initialize_state() -> Weight {
		// Approximated: similar cost class to `set_sp1_vkey_hash`, plus several writes.
		// `initialize_state` has no benchmark because it requires an ABI-encoded
		// `BeefyConsensusState` fixture; tracked under the follow-ups in
		// docs/beefy-uncle-proofs-implementation.md.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}
