/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc6160Ext20Sol from "./IERC6160Ext20.sol";
export * as iercAclCoreSol from "./IERCAclCore.sol";
