// Covers the fan-out both phantom handlers perform now that the pallet bundles every configured
// token pair into a single order: one registration writes a row per directed leg, and one bid
// window closing writes a price snapshot per leg.
//
// The SDK is mocked rather than imported. Its CJS bundle pulls in ESM-only packages that jest's
// runtime cannot require, and the aggregation itself is already covered by the SDK's own tests; what
// matters here is what the handlers do with its result.

const aggregatePhantomBids = jest.fn()

jest.mock("@hyperbridge/sdk/intents-helpers", () => ({
	aggregatePhantomBids: (...args: unknown[]) => aggregatePhantomBids(...args),
	setAggregationFetch: jest.fn(),
}))
jest.mock("@/utils/phantom-decode", () => ({
	extractFillDataVm2: jest.fn(),
	recoverBidSignerVm2: jest.fn(),
	bidNonceKeyVm2: jest.fn(),
	orderCommitmentVm2: jest.fn(),
}))
jest.mock("@/utils/safeFetch", () => ({ safeFetch: jest.fn() }))
jest.mock("@/utils/rpc.helpers", () => ({
	getBlockTimestamp: jest.fn(async () => 1_700_000_000_000),
	replaceWebsocketWithHttp: (url: string) => url.replace(/^ws/, "http"),
}))
jest.mock("@/utils/substrate.helpers", () => ({ getHostStateMachine: () => HOST }))
jest.mock("@/constants", () => ({ ENV_CONFIG: { "KUSAMA-4009": "ws://node.test", "EVM-8453": "ws://base.test" } }))
jest.mock("@/intent-gateway-v3-addresses", () => ({
	INTENT_GATEWAY_V3_ADDRESSES: { "EVM-8453": "0x2d61624A17f361020679FaA16fbB566C344AaF4B" },
}))
jest.mock("@/yield-vault-addresses", () => ({ YIELD_VAULT_ADDRESSES: {} }))
// Generated by scripts/generate-chain-yamls.ts, so it is absent from a fresh checkout.
jest.mock(
	"@/solver-account-addresses",
	() => ({ SOLVER_ACCOUNT_ADDRESSES: { "EVM-8453": "0xfCd233b937D7622AAc63ced3C9A1A12F4a6B64E3" } }),
	{ virtual: true },
)

const HOST = "KUSAMA-4009"
const CHAIN = "EVM-8453"
const COMMITMENT = `0x${"aa".repeat(32)}`
const USDC = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
const CNGN = "0x46c85152bfe9f96829aa94755d9f915f9b10ef5f"

// Minimal in-memory stand-in for the SubQuery store, so the generated entity classes run for real.
const rows = new Map<string, Map<string, any>>()
function table(entity: string): Map<string, any> {
	if (!rows.has(entity)) rows.set(entity, new Map())
	return rows.get(entity)!
}

;(global as any).logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn(), error: jest.fn() }
;(global as any).chainId = HOST
;(global as any).store = {
	get: async (entity: string, id: string) => table(entity).get(id),
	set: async (entity: string, id: string, data: unknown) => {
		table(entity).set(id, data)
	},
	getByField: async (entity: string, field: string, value: unknown) =>
		[...table(entity).values()].filter((row) => row[field] === value),
	// Equality filters only — the handlers use nothing else, and the real store supports no ranges.
	getByFields: async (entity: string, filters: [string, string, unknown][] = []) =>
		[...table(entity).values()].filter((row) =>
			filters.every(([field, op, value]) => op !== "=" || row[field] === value),
		),
	remove: async (entity: string, id: string) => {
		table(entity).delete(id)
	},
}

import { handlePhantomOrderRegistered } from "../handlePhantomOrderRegistered.handler"
import { handlePhantomOrderPrices } from "../handlePhantomOrderPrices.handler"

// polkadot-js hands the handler codec objects, not plain values.
const hex = (value: string) => ({ toHex: () => value, toString: () => value })
const num = (value: number | bigint) => ({ toString: () => value.toString() })
const pair = (tokenA: string, tokenB: string, standardAmount: bigint) => ({
	tokenA: hex(tokenA),
	tokenB: hex(tokenB),
	standardAmount: num(standardAmount),
})

function registeredEvent(pairs: unknown[]) {
	return {
		event: { data: [hex(COMMITMENT), hex(`0x${Buffer.from(CHAIN, "utf8").toString("hex")}`), num(7), pairs] },
		block: { block: { header: { hash: { toString: () => "0xblock" }, number: { toBigInt: () => 7n } } } },
	} as any
}

function windowClosedEvent(block: bigint = 11n) {
	return {
		event: { data: [hex(COMMITMENT)] },
		block: { block: { header: { hash: { toString: () => "0xblock" }, number: { toBigInt: () => block } } } },
	} as any
}

// A priced leg as aggregatePhantomBids reports it. Solvers default to one anonymous bidder so the
// pool pipeline always has someone behind a quote.
function leg(
	legIndex: number,
	outputToken: string,
	medianPrice: bigint,
	bidders: { solver: string; weight: bigint; acceptedSources: string[] | null }[] = [
		{ solver: "0xsolver", weight: 0n, acceptedSources: null },
	],
) {
	return {
		legIndex,
		outputToken,
		lowestPrice: medianPrice,
		highestPrice: medianPrice,
		medianPrice,
		bidCount: bidders.length,
		bidders,
	}
}

beforeEach(() => {
	rows.clear()
	aggregatePhantomBids.mockReset()
})

describe("handlePhantomOrderRegistered", () => {
	it("writes one pair row per leg, keyed and indexed by the leg's position", async () => {
		await handlePhantomOrderRegistered(registeredEvent([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 10n ** 6n)]))

		const order = table("PhantomOrderV2").get(COMMITMENT)
		expect(order).toMatchObject({ id: COMMITMENT, chain: CHAIN, createdAtBlock: 7n })

		const pairs = [...table("PhantomOrderLeg").values()]
		expect(pairs).toHaveLength(2)
		expect(pairs.map((p) => p.id)).toEqual([`${COMMITMENT}-0`, `${COMMITMENT}-1`])
		expect(pairs.map((p) => p.legIndex)).toEqual([0, 1])
		expect(pairs.every((p) => p.orderId === COMMITMENT)).toBe(true)
		// Both directions of the same pair are distinct legs.
		expect(pairs.map((p) => [p.tokenA, p.tokenB])).toEqual([
			[USDC, CNGN],
			[CNGN, USDC],
		])
	})

	it("ignores a repeat registration of the same commitment", async () => {
		await handlePhantomOrderRegistered(registeredEvent([pair(USDC, CNGN, 1_000_000n)]))
		await handlePhantomOrderRegistered(registeredEvent([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1n)]))

		expect([...table("PhantomOrderLeg").values()]).toHaveLength(1)
	})
})

describe("handlePhantomOrderPrices", () => {
	async function register(pairs: unknown[]) {
		await handlePhantomOrderRegistered(registeredEvent(pairs))
	}

	it("writes a snapshot per priced leg, each carrying its own pair's tokens", async () => {
		await register([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				leg(0, CNGN, 1_500n, [
					{ solver: "0xs1", weight: 0n, acceptedSources: null },
					{ solver: "0xs2", weight: 0n, acceptedSources: null },
					{ solver: "0xs3", weight: 0n, acceptedSources: null },
				]),
				leg(1, USDC, 660n, [
					{ solver: "0xs1", weight: 0n, acceptedSources: null },
					{ solver: "0xs2", weight: 0n, acceptedSources: null },
				]),
			],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const snapshots = [...table("PhantomOrderPriceSnapshotV2").values()]
		expect(snapshots).toHaveLength(2)
		expect(snapshots.map((s) => s.id)).toEqual([`${COMMITMENT}-11-0`, `${COMMITMENT}-11-1`])
		// The snapshot's tokens come from its own leg, not from the first pair on the order.
		expect(snapshots.map((s) => [s.tokenA, s.tokenB])).toEqual([
			[USDC, CNGN],
			[CNGN, USDC],
		])
		expect(snapshots.map((s) => s.medianPrice)).toEqual([1_500n, 660n])
		expect(snapshots.map((s) => s.bidCount)).toEqual([3, 2])
		expect(snapshots.map((s) => s.legId)).toEqual([`${COMMITMENT}-0`, `${COMMITMENT}-1`])
	})

	it("prices only the legs solvers quoted, leaving the rest without a snapshot", async () => {
		await register([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(1, USDC, 660n)],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const snapshots = [...table("PhantomOrderPriceSnapshotV2").values()]
		expect(snapshots).toHaveLength(1)
		expect(snapshots[0].id).toBe(`${COMMITMENT}-11-1`)
		expect(snapshots[0].tokenA).toBe(CNGN)
	})

	it("does not rewrite snapshots when the same window close is replayed", async () => {
		await register([pair(USDC, CNGN, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, CNGN, 1n)],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())
		await handlePhantomOrderPrices(windowClosedEvent())

		expect(aggregatePhantomBids).toHaveBeenCalledTimes(1)
		expect([...table("PhantomOrderPriceSnapshotV2").values()]).toHaveLength(1)
	})

	it("skips a priced leg with no registered pair rather than mislabelling it", async () => {
		await register([pair(USDC, CNGN, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(4, CNGN, 1n)],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		expect([...table("PhantomOrderPriceSnapshotV2").values()]).toHaveLength(0)
	})

	it("records each bidding solver's swept balances once, not once per leg", async () => {
		await register([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, CNGN, 1n), leg(1, USDC, 2n)],
			lpBalances: [{ solver: "0xsolver", chain: CHAIN, tokenAddress: CNGN, balance: 42n }],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		expect([...table("LiquidityProvider").values()]).toHaveLength(1)
		expect([...table("LiquidityProviderBalance").values()]).toHaveLength(1)
	})
})

// Both tokens live on Base in these tests: cNGN and USDC are registry-tracked with 6 decimals, so
// rates and depths normalize by 10^(18-6) = 1e12.
const SCALE = 10n ** 12n

describe("handlePhantomOrderPrices pool pipeline", () => {
	async function register(pairs: unknown[]) {
		await handlePhantomOrderRegistered(registeredEvent(pairs))
	}

	it("merges both directions of a pair into one pool with sell and buy sides", async () => {
		await register([pair(CNGN, USDC, 1_000_000n), pair(USDC, CNGN, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				// cNGN -> USDC is the SELL side (cNGN sorts first), USDC -> cNGN the BUY side.
				leg(0, USDC, 660n, [{ solver: "0xa", weight: 100n, acceptedSources: null }]),
				leg(1, CNGN, 1_500n, [{ solver: "0xa", weight: 40n, acceptedSources: null }]),
			],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const pool = table("LiquidityPool").get("cNGN-USDC")
		expect(pool).toMatchObject({
			token0Symbol: "cNGN",
			token1Symbol: "USDC",
			sellRate: 660n * SCALE,
			buyRate: 1_500n * SCALE,
			sellDepth: 100n * SCALE,
			buyDepth: 40n * SCALE,
			sellBidCount: 1,
			buyBidCount: 1,
			lastUpdatedBlock: 11n,
		})

		const chainRows = [...table("PoolChainLiquidity").values()]
		expect(chainRows.map((r) => r.id).sort()).toEqual([
			`cNGN-USDC-${CHAIN}-BUY`,
			`cNGN-USDC-${CHAIN}-SELL`,
		])

		const snapshots = [...table("PhantomOrderPriceSnapshotV2").values()]
		expect(snapshots.map((s) => [s.poolId, s.direction, s.chain])).toEqual([
			["cNGN-USDC", "SELL", CHAIN],
			["cNGN-USDC", "BUY", CHAIN],
		])
	})

	it("leaves the other side null for a pair registered in one direction only", async () => {
		await register([pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, USDC, 660n, [{ solver: "0xa", weight: 5n, acceptedSources: null }])],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const pool = table("LiquidityPool").get("cNGN-USDC")
		expect(pool.sellRate).toBe(660n * SCALE)
		expect(pool.buyRate).toBeUndefined()
		expect(pool.buyDepth).toBe(0n)
	})

	it("keeps the snapshot but skips pool work when a leg token is not registry-tracked", async () => {
		const unknownToken = "0x1111111111111111111111111111111111111111"
		await register([pair(unknownToken, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, USDC, 660n)],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const snapshots = [...table("PhantomOrderPriceSnapshotV2").values()]
		expect(snapshots).toHaveLength(1)
		expect(snapshots[0].poolId).toBeUndefined()
		expect(snapshots[0].direction).toBeUndefined()
		expect(table("LiquidityPool").size).toBe(0)
	})

	it("skips pool work when the standard amount disagrees with the registry decimals", async () => {
		// cNGN is 6-decimal; a 1e18 standard amount means the pallet config and registry disagree,
		// and any rate derived from it would be off by an integer factor.
		await register([pair(CNGN, USDC, 10n ** 18n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, USDC, 660n)],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		expect([...table("PhantomOrderPriceSnapshotV2").values()]).toHaveLength(1)
		expect(table("LiquidityPool").size).toBe(0)
	})

	it("records bidders with their declarations and removes ones that stop bidding", async () => {
		await register([pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				leg(0, USDC, 660n, [
					{ solver: "0xa", weight: 10n, acceptedSources: ["EVM-1", "EVM-56"] },
					{ solver: "0xb", weight: 20n, acceptedSources: null },
				]),
			],
			lpBalances: [],
		})
		await handlePhantomOrderPrices(windowClosedEvent(11n))

		let bidders = [...table("PoolBidder").values()]
		expect(bidders).toHaveLength(2)
		expect(bidders.find((b) => b.providerId === "0xa")).toMatchObject({
			acceptedSources: ["EVM-1", "EVM-56"],
			liquidity: 10n * SCALE,
			direction: "SELL",
		})
		expect(bidders.find((b) => b.providerId === "0xb")!.acceptedSources).toBeUndefined()
		// Bidders get provider rows even when the balance sweep recorded nothing for them.
		expect(table("LiquidityProvider").size).toBe(2)

		// Next window only 0xa bids: 0xb's row must go, not linger as a live-looking route.
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, USDC, 700n, [{ solver: "0xa", weight: 15n, acceptedSources: ["EVM-1"] }])],
			lpBalances: [],
		})
		await handlePhantomOrderPrices(windowClosedEvent(22n))

		bidders = [...table("PoolBidder").values()]
		expect(bidders).toHaveLength(1)
		expect(bidders[0]).toMatchObject({ providerId: "0xa", liquidity: 15n * SCALE, acceptedSources: ["EVM-1"] })
	})

	it("zeroes depth but keeps the last rate when a registered pair goes unquoted", async () => {
		await register([pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(0, USDC, 660n, [{ solver: "0xa", weight: 10n, acceptedSources: null }])],
			lpBalances: [],
		})
		await handlePhantomOrderPrices(windowClosedEvent(11n))

		// The window closes with bids from someone, but nobody quoted this pair's leg.
		aggregatePhantomBids.mockResolvedValue({
			legs: [leg(4, USDC, 1n)],
			lpBalances: [],
		})
		await handlePhantomOrderPrices(windowClosedEvent(22n))

		const row = table("PoolChainLiquidity").get(`cNGN-USDC-${CHAIN}-SELL`)
		expect(row).toMatchObject({ rate: 660n * SCALE, depth: 0n, bidCount: 0, lastUpdatedBlock: 22n })

		const pool = table("LiquidityPool").get("cNGN-USDC")
		expect(pool.sellRate).toBe(660n * SCALE)
		expect(pool.sellDepth).toBe(0n)
	})
})
