// Covers the fan-out both phantom handlers perform now that the pallet bundles every configured
// token pair into a single order: one registration writes a pair row per leg, and one bid window
// closing writes a price snapshot per leg.
//
// The SDK is mocked rather than imported. Its CJS bundle pulls in ESM-only packages that jest's
// runtime cannot require, and the aggregation itself is already covered by the SDK's own tests; what
// matters here is what the handlers do with its result.

const aggregatePhantomBids = jest.fn()

jest.mock("@hyperbridge/sdk/intents-helpers", () => ({
	aggregatePhantomBids: (...args: unknown[]) => aggregatePhantomBids(...args),
	setAggregationFetch: jest.fn(),
}))
jest.mock("@/utils/phantom-decode", () => ({
	extractFillDataVm2: jest.fn(),
	recoverBidSignerVm2: jest.fn(),
	bidNonceKeyVm2: jest.fn(),
	orderCommitmentVm2: jest.fn(),
}))
jest.mock("@/utils/safeFetch", () => ({ safeFetch: jest.fn() }))
jest.mock("@/utils/rpc.helpers", () => ({
	getBlockTimestamp: jest.fn(async () => 1_700_000_000_000),
	replaceWebsocketWithHttp: (url: string) => url.replace(/^ws/, "http"),
}))
jest.mock("@/utils/substrate.helpers", () => ({ getHostStateMachine: () => HOST }))
jest.mock("@/constants", () => ({ ENV_CONFIG: { "KUSAMA-4009": "ws://node.test", "EVM-8453": "ws://base.test" } }))
jest.mock("@/intent-gateway-v3-addresses", () => ({
	INTENT_GATEWAY_V3_ADDRESSES: { "EVM-8453": "0x2d61624A17f361020679FaA16fbB566C344AaF4B" },
}))
jest.mock("@/yield-vault-addresses", () => ({ YIELD_VAULT_ADDRESSES: {} }))
// Generated by scripts/generate-chain-yamls.ts, so it is absent from a fresh checkout.
jest.mock(
	"@/solver-account-addresses",
	() => ({ SOLVER_ACCOUNT_ADDRESSES: { "EVM-8453": "0xfCd233b937D7622AAc63ced3C9A1A12F4a6B64E3" } }),
	{ virtual: true },
)

const HOST = "KUSAMA-4009"
const CHAIN = "EVM-8453"
const COMMITMENT = `0x${"aa".repeat(32)}`
const USDC = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
const CNGN = "0x46c85152bfe9f96829aa94755d9f915f9b10ef5f"

// Minimal in-memory stand-in for the SubQuery store, so the generated entity classes run for real.
const rows = new Map<string, Map<string, any>>()
function table(entity: string): Map<string, any> {
	if (!rows.has(entity)) rows.set(entity, new Map())
	return rows.get(entity)!
}

;(global as any).logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn(), error: jest.fn() }
;(global as any).chainId = HOST
;(global as any).store = {
	get: async (entity: string, id: string) => table(entity).get(id),
	set: async (entity: string, id: string, data: unknown) => {
		table(entity).set(id, data)
	},
	getByField: async (entity: string, field: string, value: unknown) =>
		[...table(entity).values()].filter((row) => row[field] === value),
	getByFields: async (entity: string) => [...table(entity).values()],
	remove: async (entity: string, id: string) => {
		table(entity).delete(id)
	},
}

import { handlePhantomOrderRegistered } from "../handlePhantomOrderRegistered.handler"
import { handlePhantomOrderPrices } from "../handlePhantomOrderPrices.handler"

// polkadot-js hands the handler codec objects, not plain values.
const hex = (value: string) => ({ toHex: () => value, toString: () => value })
const num = (value: number | bigint) => ({ toString: () => value.toString() })
const pair = (tokenA: string, tokenB: string, standardAmount: bigint) => ({
	tokenA: hex(tokenA),
	tokenB: hex(tokenB),
	standardAmount: num(standardAmount),
})

function registeredEvent(pairs: unknown[]) {
	return {
		event: { data: [hex(COMMITMENT), hex(`0x${Buffer.from(CHAIN, "utf8").toString("hex")}`), num(7), pairs] },
		block: { block: { header: { hash: { toString: () => "0xblock" }, number: { toBigInt: () => 7n } } } },
	} as any
}

function windowClosedEvent() {
	return {
		event: { data: [hex(COMMITMENT)] },
		block: { block: { header: { hash: { toString: () => "0xblock" }, number: { toBigInt: () => 11n } } } },
	} as any
}

beforeEach(() => {
	rows.clear()
	aggregatePhantomBids.mockReset()
})

describe("handlePhantomOrderRegistered", () => {
	it("writes one pair row per leg, keyed and indexed by the leg's position", async () => {
		await handlePhantomOrderRegistered(registeredEvent([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 10n ** 6n)]))

		const order = table("PhantomOrder").get(COMMITMENT)
		expect(order).toMatchObject({ id: COMMITMENT, chain: CHAIN, createdAtBlock: 7n })

		const pairs = [...table("PhantomOrderPair").values()]
		expect(pairs).toHaveLength(2)
		expect(pairs.map((p) => p.id)).toEqual([`${COMMITMENT}-0`, `${COMMITMENT}-1`])
		expect(pairs.map((p) => p.pairIndex)).toEqual([0, 1])
		expect(pairs.every((p) => p.orderId === COMMITMENT)).toBe(true)
		// Both directions of the same pair are distinct legs.
		expect(pairs.map((p) => [p.tokenA, p.tokenB])).toEqual([
			[USDC, CNGN],
			[CNGN, USDC],
		])
	})

	it("ignores a repeat registration of the same commitment", async () => {
		await handlePhantomOrderRegistered(registeredEvent([pair(USDC, CNGN, 1_000_000n)]))
		await handlePhantomOrderRegistered(registeredEvent([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1n)]))

		expect([...table("PhantomOrderPair").values()]).toHaveLength(1)
	})
})

describe("handlePhantomOrderPrices", () => {
	async function register(pairs: unknown[]) {
		await handlePhantomOrderRegistered(registeredEvent(pairs))
	}

	it("writes a snapshot per priced leg, each carrying its own pair's tokens", async () => {
		await register([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				{ pairIndex: 0, outputToken: CNGN, lowestPrice: 1_500n, highestPrice: 1_500n, medianPrice: 1_500n, bidCount: 3 },
				{ pairIndex: 1, outputToken: USDC, lowestPrice: 660n, highestPrice: 660n, medianPrice: 660n, bidCount: 2 },
			],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const snapshots = [...table("PhantomOrderPriceSnapshot").values()]
		expect(snapshots).toHaveLength(2)
		expect(snapshots.map((s) => s.id)).toEqual([`${COMMITMENT}-11-0`, `${COMMITMENT}-11-1`])
		// The snapshot's tokens come from its own leg, not from the first pair on the order.
		expect(snapshots.map((s) => [s.tokenA, s.tokenB])).toEqual([
			[USDC, CNGN],
			[CNGN, USDC],
		])
		expect(snapshots.map((s) => s.medianPrice)).toEqual([1_500n, 660n])
		expect(snapshots.map((s) => s.bidCount)).toEqual([3, 2])
		expect(snapshots.map((s) => s.pairId)).toEqual([`${COMMITMENT}-0`, `${COMMITMENT}-1`])
	})

	it("prices only the legs solvers quoted, leaving the rest without a snapshot", async () => {
		await register([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				{ pairIndex: 1, outputToken: USDC, lowestPrice: 660n, highestPrice: 660n, medianPrice: 660n, bidCount: 1 },
			],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		const snapshots = [...table("PhantomOrderPriceSnapshot").values()]
		expect(snapshots).toHaveLength(1)
		expect(snapshots[0].id).toBe(`${COMMITMENT}-11-1`)
		expect(snapshots[0].tokenA).toBe(CNGN)
	})

	it("does not rewrite snapshots when the same window close is replayed", async () => {
		await register([pair(USDC, CNGN, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				{ pairIndex: 0, outputToken: CNGN, lowestPrice: 1n, highestPrice: 1n, medianPrice: 1n, bidCount: 1 },
			],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())
		await handlePhantomOrderPrices(windowClosedEvent())

		expect(aggregatePhantomBids).toHaveBeenCalledTimes(1)
		expect([...table("PhantomOrderPriceSnapshot").values()]).toHaveLength(1)
	})

	it("skips a priced leg with no registered pair rather than mislabelling it", async () => {
		await register([pair(USDC, CNGN, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				{ pairIndex: 4, outputToken: CNGN, lowestPrice: 1n, highestPrice: 1n, medianPrice: 1n, bidCount: 1 },
			],
			lpBalances: [],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		expect([...table("PhantomOrderPriceSnapshot").values()]).toHaveLength(0)
	})

	it("records each bidding solver's swept balances once, not once per leg", async () => {
		await register([pair(USDC, CNGN, 1_000_000n), pair(CNGN, USDC, 1_000_000n)])
		aggregatePhantomBids.mockResolvedValue({
			legs: [
				{ pairIndex: 0, outputToken: CNGN, lowestPrice: 1n, highestPrice: 1n, medianPrice: 1n, bidCount: 1 },
				{ pairIndex: 1, outputToken: USDC, lowestPrice: 2n, highestPrice: 2n, medianPrice: 2n, bidCount: 1 },
			],
			lpBalances: [{ solver: "0xsolver", chain: CHAIN, tokenAddress: CNGN, balance: 42n }],
		})

		await handlePhantomOrderPrices(windowClosedEvent())

		expect([...table("LiquidityProvider").values()]).toHaveLength(1)
		expect([...table("LiquidityProviderBalance").values()]).toHaveLength(1)
	})
})
