// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `cumulus_pallet_xcmp_queue`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-04-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `polytope-labs`, CPU: `AMD Ryzen Threadripper PRO 5995WX 64-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=cumulus_pallet_xcmp_queue
// --extrinsic=*
// --steps=50
// --repeat=20
// --unsafe-overwrite-results
// --genesis-builder-preset=development
// --template=./scripts/template.hbs
// --genesis-builder=runtime
// --runtime=./target/release/wbuild/nexus-runtime/nexus_runtime.compact.wasm
// --output
// parachain/runtimes/nexus/src/weights/cumulus_pallet_xcmp_queue.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `cumulus_pallet_xcmp_queue`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> cumulus_pallet_xcmp_queue::WeightInfo for WeightInfo<T> {
	fn set_config_with_u32() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `213`
		//  Estimated: `0`
		// Minimum execution time: 7_855_000 picoseconds.
		Weight::from_parts(8_336_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 65531]`.
	fn enqueue_n_bytes_xcmp_message(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219`
		//  Estimated: `0`
		// Minimum execution time: 18_465_000 picoseconds.
		Weight::from_parts(11_336_136, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 27
			.saturating_add(Weight::from_parts(911, 0).saturating_mul(n.into()))
	}
	/// The range of component `n` is `[0, 1000]`.
	fn enqueue_n_empty_xcmp_messages(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219`
		//  Estimated: `0`
		// Minimum execution time: 18_625_000 picoseconds.
		Weight::from_parts(34_736_142, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 2_717
			.saturating_add(Weight::from_parts(201_469, 0).saturating_mul(n.into()))
	}
	/// The range of component `n` is `[0, 65521]`.
	fn enqueue_empty_xcmp_message_at(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `401 + n * (1 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 28_734_000 picoseconds.
		Weight::from_parts(36_325_073, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 16
			.saturating_add(Weight::from_parts(1_057, 0).saturating_mul(n.into()))
	}
	/// The range of component `n` is `[0, 100]`.
	fn enqueue_n_full_pages(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `253`
		//  Estimated: `0`
		// Minimum execution time: 16_411_000 picoseconds.
		Weight::from_parts(124_249_542, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 293_245
			.saturating_add(Weight::from_parts(26_298_639, 0).saturating_mul(n.into()))
	}
	fn enqueue_1000_small_xcmp_messages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `33166`
		//  Estimated: `0`
		// Minimum execution time: 210_359_000 picoseconds.
		Weight::from_parts(238_934_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn suspend_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `213`
		//  Estimated: `0`
		// Minimum execution time: 5_190_000 picoseconds.
		Weight::from_parts(11_442_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn resume_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `0`
		// Minimum execution time: 11_212_000 picoseconds.
		Weight::from_parts(13_326_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 92]`.
	fn take_first_concatenated_xcm(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_775_000 picoseconds.
		Weight::from_parts(4_127_236, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 1_671
			.saturating_add(Weight::from_parts(21_584, 0).saturating_mul(n.into()))
	}
	fn on_idle_good_msg() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `65848`
		//  Estimated: `0`
		// Minimum execution time: 80_092_000 picoseconds.
		Weight::from_parts(81_154_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_idle_large_msg() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `65847`
		//  Estimated: `0`
		// Minimum execution time: 51_518_000 picoseconds.
		Weight::from_parts(52_390_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
