// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_intents_coprocessor`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `harsh.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=pallet_intents_coprocessor
// --extrinsic=*
// --steps=50
// --repeat=20
// --unsafe-overwrite-results
// --genesis-builder-preset=development
// --template=./scripts/template.hbs
// --genesis-builder=runtime
// --runtime=./target/release/wbuild/nexus-runtime/nexus_runtime.compact.wasm
// --output
// parachain/runtimes/nexus/src/weights/pallet_intents_coprocessor.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_intents_coprocessor`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_intents_coprocessor::WeightInfo for WeightInfo<T> {
	/// Storage: `IntentsCoprocessor::CurrentPhantomOrder` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::CurrentPhantomOrder` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::Bids` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Bids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::StorageDepositFee` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::StorageDepositFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn place_bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3607`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3607))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Bids` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Bids` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn retract_bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `280`
		//  Estimated: `3745`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3745))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:2 w:1)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_deployment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `6086`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6086))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cfc4a36f0dfb70382708d5bc152d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cfc4a36f0dfb70382708d5bc152d` (r:1 w:1)
	fn update_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866`
		//  Estimated: `4331`
		// Minimum execution time: 33_000_000 picoseconds.
		Weight::from_parts(38_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4331))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e6e8c09efb35a07dc00774806bcd` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473e6e8c09efb35a07dc00774806bcd` (r:1 w:1)
	fn sweep_dust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866`
		//  Estimated: `4331`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4331))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739b6e6c162f79ff72601b50ddcc2c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739b6e6c162f79ff72601b50ddcc2c` (r:1 w:1)
	fn upgrade_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866`
		//  Estimated: `4331`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4331))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Paymasters` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::Paymasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_paymaster_deployment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `IntentsCoprocessor::Paymasters` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Paymasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736cc277ee780e83dedbe1a6e5a797` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74736cc277ee780e83dedbe1a6e5a797` (r:1 w:1)
	fn upgrade_paymaster() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `738`
		//  Estimated: `4203`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4203))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Paymasters` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Paymasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cb139a6a51c91d4d67c1213d4e47` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473cb139a6a51c91d4d67c1213d4e47` (r:1 w:1)
	fn update_paymaster_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `738`
		//  Estimated: `4203`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(34_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4203))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Paymasters` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Paymasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473eb5c0495fe982ec911942422631d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473eb5c0495fe982ec911942422631d` (r:1 w:1)
	fn register_paymaster_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `738`
		//  Estimated: `4203`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4203))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Paymasters` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Paymasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747314c0537e633551c727ce6b0bd2a0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747314c0537e633551c727ce6b0bd2a0` (r:1 w:1)
	fn deactivate_paymaster_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `738`
		//  Estimated: `4203`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(32_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4203))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Paymasters` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Paymasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c4382627d82b4ebb62f3cc8c6265` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473c4382627d82b4ebb62f3cc8c6265` (r:1 w:1)
	fn withdraw_paymaster_assets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `738`
		//  Estimated: `4203`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(32_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4203))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::Gateways` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::Gateways` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::CounterForIntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::CounterForIntermediateLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mmr::NumberOfLeaves` (r:1 w:0)
	/// Proof: `Mmr::NumberOfLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Mmr::IntermediateLeaves` (r:1 w:1)
	/// Proof: `Mmr::IntermediateLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731c023622c98128a1e9a16c60652e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74731c023622c98128a1e9a16c60652e` (r:1 w:1)
	fn update_token_decimals() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866`
		//  Estimated: `4331`
		// Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(34_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4331))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `IntentsCoprocessor::PhantomBidWindow` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::PhantomBidWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::PhantomOrderConfig` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::PhantomOrderConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::CurrentPhantomOrder` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::CurrentPhantomOrder` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::LastPhantomGeneration` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::LastPhantomGeneration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_phantom_order_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1627`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(24_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1627))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `IntentsCoprocessor::PhantomOrderConfig` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::PhantomOrderConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::LastPhantomGeneration` (r:1 w:1)
	/// Proof: `IntentsCoprocessor::LastPhantomGeneration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::LatestStateMachineHeight` (r:1 w:0)
	/// Proof: `Ismp::LatestStateMachineHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::CurrentPhantomOrder` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::CurrentPhantomOrder` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 64]`.
	fn generate_phantom_order(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462 + p * (72 ±0)`
		//  Estimated: `3927 + p * (72 ±0)`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_685_722, 0)
			.saturating_add(Weight::from_parts(0, 3927))
			// Standard Error: 215
			.saturating_add(Weight::from_parts(880_044, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(Weight::from_parts(0, 72).saturating_mul(p.into()))
	}
	/// Storage: `IntentsCoprocessor::PhantomOrderConfig` (r:1 w:0)
	/// Proof: `IntentsCoprocessor::PhantomOrderConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `IntentsCoprocessor::PhantomBidWindow` (r:0 w:1)
	/// Proof: `IntentsCoprocessor::PhantomBidWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_phantom_bid_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1627`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1627))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
