/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IDispatcher, IDispatcherInterface } from "../../ismp/IDispatcher";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "height",
            type: "uint64",
          },
          {
            internalType: "bytes[]",
            name: "keys",
            type: "bytes[]",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchGet",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes",
                name: "source",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "dest",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "nonce",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "from",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "to",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "timeoutTimestamp",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "body",
                type: "bytes",
              },
            ],
            internalType: "struct PostRequest",
            name: "request",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "response",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchPostResponse",
        name: "response",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchPost",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDispatcher__factory {
  static readonly abi = _abi;
  static createInterface(): IDispatcherInterface {
    return new Interface(_abi) as IDispatcherInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDispatcher {
    return new Contract(address, _abi, runner) as unknown as IDispatcher;
  }
}
