/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IIsmpHost, IIsmpHostInterface } from "../../ismp/IIsmpHost";

const _abi = [
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "challengePeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "consensusClient",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "consensusState",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "consensusUpdateTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "height",
            type: "uint64",
          },
          {
            internalType: "bytes[]",
            name: "keys",
            type: "bytes[]",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchGet",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes",
                name: "source",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "dest",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "nonce",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "from",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "to",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "timeoutTimestamp",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "body",
                type: "bytes",
              },
            ],
            internalType: "struct PostRequest",
            name: "request",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "response",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchPostResponse",
        name: "response",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchPost",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes",
                name: "source",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "dest",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "nonce",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "from",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "to",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "timeoutTimestamp",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "body",
                type: "bytes",
              },
            ],
            internalType: "struct PostRequest",
            name: "request",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "response",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
        ],
        internalType: "struct PostResponse",
        name: "response",
        type: "tuple",
      },
    ],
    name: "dispatchIncoming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes",
                name: "source",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "dest",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "nonce",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "from",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "to",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "timeoutTimestamp",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "body",
                type: "bytes",
              },
            ],
            internalType: "struct PostRequest",
            name: "request",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "response",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
        ],
        internalType: "struct PostResponse",
        name: "timeout",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct FeeMetadata",
        name: "meta",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "dispatchIncoming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "source",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "from",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
        ],
        internalType: "struct PostRequest",
        name: "timeout",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct FeeMetadata",
        name: "meta",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "dispatchIncoming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "source",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "from",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
        ],
        internalType: "struct PostRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatchIncoming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "source",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "from",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes[]",
            name: "keys",
            type: "bytes[]",
          },
          {
            internalType: "uint64",
            name: "height",
            type: "uint64",
          },
        ],
        internalType: "struct GetRequest",
        name: "timeout",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct FeeMetadata",
        name: "meta",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "dispatchIncoming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes",
                name: "source",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "dest",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "nonce",
                type: "uint64",
              },
              {
                internalType: "bytes",
                name: "from",
                type: "bytes",
              },
              {
                internalType: "uint64",
                name: "timeoutTimestamp",
                type: "uint64",
              },
              {
                internalType: "bytes[]",
                name: "keys",
                type: "bytes[]",
              },
              {
                internalType: "uint64",
                name: "height",
                type: "uint64",
              },
            ],
            internalType: "struct GetRequest",
            name: "request",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bytes",
                name: "key",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "value",
                type: "bytes",
              },
            ],
            internalType: "struct StorageValue[]",
            name: "values",
            type: "tuple[]",
          },
        ],
        internalType: "struct GetResponse",
        name: "response",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct FeeMetadata",
        name: "meta",
        type: "tuple",
      },
    ],
    name: "dispatchIncoming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "feeToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "frozen",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "host",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestStateMachineHeight",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "perByteFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "requestCommitments",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct FeeMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "requestReceipts",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "responseCommitments",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct FeeMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "responseReceipts",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "responseCommitment",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "relayer",
            type: "address",
          },
        ],
        internalType: "struct ResponseReceipt",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "stateMachineId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "height",
            type: "uint256",
          },
        ],
        internalType: "struct StateMachineHeight",
        name: "height",
        type: "tuple",
      },
    ],
    name: "stateMachineCommitment",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "overlayRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "stateRoot",
            type: "bytes32",
          },
        ],
        internalType: "struct StateCommitment",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "stateMachineId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "height",
            type: "uint256",
          },
        ],
        internalType: "struct StateMachineHeight",
        name: "height",
        type: "tuple",
      },
    ],
    name: "stateMachineCommitmentUpdateTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "state",
        type: "bytes",
      },
    ],
    name: "storeConsensusState",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "storeConsensusUpdateTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "height",
        type: "uint256",
      },
    ],
    name: "storeLatestStateMachineHeight",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "stateMachineId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "height",
            type: "uint256",
          },
        ],
        internalType: "struct StateMachineHeight",
        name: "height",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "overlayRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "stateRoot",
            type: "bytes32",
          },
        ],
        internalType: "struct StateCommitment",
        name: "commitment",
        type: "tuple",
      },
    ],
    name: "storeStateMachineCommitment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "stateMachineId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "height",
            type: "uint256",
          },
        ],
        internalType: "struct StateMachineHeight",
        name: "height",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "storeStateMachineCommitmentUpdateTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "timestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unStakingPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIsmpHost__factory {
  static readonly abi = _abi;
  static createInterface(): IIsmpHostInterface {
    return new Interface(_abi) as IIsmpHostInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IIsmpHost {
    return new Contract(address, _abi, runner) as unknown as IIsmpHost;
  }
}
