import type { FillerTomlConfig, ChainConfirmationPolicy } from "@/config/filler-toml"
import type { PairConfig } from "@/config/pairs"

export interface EmitOptions {
	/** Comment shown above each [[chains]] entry, aligned with config.chains. */
	chainComments?: string[]
}

/**
 * Renders a FillerTomlConfig as a commented TOML document. A generic stringifier
 * can't produce comments or stable section ordering, so the document is emitted
 * section by section; `toml.parse(emitFillerToml(c))` must deep-equal `c`.
 */
export function emitFillerToml(config: FillerTomlConfig, options: EmitOptions = {}): string {
	const out: string[] = []
	const push = (line = "") => out.push(line)

	push("# Simplex filler configuration")
	push("# Generated by `simplex init`. Safe to edit by hand; re-run `simplex init` to update interactively.")
	push()

	push("[simplex]")
	push("# Maximum number of orders processed concurrently. Lower this if your RPCs rate-limit (429s).")
	push(kv("maxConcurrentOrders", config.simplex.maxConcurrentOrders))
	if (config.simplex.logging !== undefined) {
		push("# Log verbosity: trace, debug, info, warn, error")
		push(kv("logging", config.simplex.logging))
	}
	if (config.simplex.watchOnly !== undefined) {
		push("# Watch-only mode: monitor orders without filling. Boolean (global) or per-chain map.")
		push(kv("watchOnly", config.simplex.watchOnly))
	}
	push("# Substrate account (hex seed or mnemonic) that signs bid extrinsics on Hyperbridge.")
	push("# It must hold BRIDGE tokens for fees; fees are claimed back automatically after fills.")
	push(kv("substratePrivateKey", config.simplex.substratePrivateKey))
	push("# Hyperbridge WebSocket endpoint used to submit solver bids.")
	push(kv("hyperbridgeWsUrl", config.simplex.hyperbridgeWsUrl))
	if (config.simplex.entryPointAddress !== undefined) {
		push(kv("entryPointAddress", config.simplex.entryPointAddress))
	}
	if (config.simplex.solverAccountContractAddress !== undefined) {
		push(kv("solverAccountContractAddress", config.simplex.solverAccountContractAddress))
	}
	if (config.simplex.targetGasUnits !== undefined) {
		push("# Gas units to keep deposited at the ERC-4337 EntryPoint on chains without a paymaster.")
		push(kv("targetGasUnits", config.simplex.targetGasUnits))
	}
	push()

	if (config.simplex.signer) {
		push("# Wallet that signs fills and holds the stablecoin float on every chain.")
		push("# WARNING: contains secrets - keep this file private (chmod 600) and never commit it.")
		push("[simplex.signer]")
		for (const [key, value] of Object.entries(config.simplex.signer)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	}

	if (config.simplex.gasFeeBump) {
		push("# Percentages added on top of the base gasPrice for UserOperations.")
		push("# Higher values win more fill races but cost more gas.")
		push("[simplex.gasFeeBump]")
		for (const [key, value] of Object.entries(config.simplex.gasFeeBump)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	} else {
		push("# Gas fee bump defaults apply: 8% priority fee, 10% max fee on top of base gasPrice.")
		push("# [simplex.gasFeeBump]")
		push("# maxPriorityFeePerGasBumpPercent = 8")
		push("# maxFeePerGasBumpPercent = 10")
		push()
	}

	if (config.simplex.overfillProtection) {
		push("# Bounds per-leg loss when internal pricing is wrong (bug, stale cache, manipulated venue).")
		push("[simplex.overfillProtection]")
		for (const [key, value] of Object.entries(config.simplex.overfillProtection)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	} else {
		push("# Overfill protection defaults apply: output clamped at 5% above the user-requested")
		push("# amount, halt after 3 consecutive clamped orders.")
		push("# [simplex.overfillProtection]")
		push("# maxOverfillBps = 500")
		push("# maxConsecutiveClamps = 3")
		push()
	}

	push("# How often a not-yet-fillable order is re-checked before being dropped.")
	push("[simplex.queue]")
	push(kv("maxRechecks", config.simplex.queue.maxRechecks))
	push(kv("recheckDelayMs", config.simplex.queue.recheckDelayMs))
	push()

	if (config.rebalancing) {
		push("# Rebalancing: triggers when a balance falls to (1 - triggerPercentage) * baseBalance.")
		push("[rebalancing]")
		push(kv("triggerPercentage", config.rebalancing.triggerPercentage))
		push()
		for (const [symbol, balances] of Object.entries(config.rebalancing.baseBalances)) {
			if (!balances) continue
			push(`[rebalancing.baseBalances.${/^[A-Za-z0-9_-]+$/.test(symbol) ? symbol : JSON.stringify(symbol)}]`)
			for (const [chainId, amount] of Object.entries(balances)) {
				push(kv(chainId, amount, true))
			}
			push()
		}
	}

	if (config.binance) {
		push("# Binance CEX rebalancing credentials.")
		push("[binance]")
		for (const [key, value] of Object.entries(config.binance)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	}

	if (config.keeper) {
		push("# SimplexPaymaster fee-recycling keeper (`paymaster-keeper` subcommand).")
		push("[keeper]")
		for (const [key, value] of Object.entries(config.keeper)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	}

	if (config.vault) {
		push("# ERC-4626 stablecoin treasury: fills source missing balance from these vaults atomically,")
		push("# and wallet balance above `threshold` is swept back down to `minBalance` to earn yield.")
		push("[vault]")
		if (config.vault.sweepIntervalMs !== undefined) {
			push(kv("sweepIntervalMs", config.vault.sweepIntervalMs))
		}
		if (config.vault.vaults?.length) {
			push("vaults = [")
			for (const vault of config.vault.vaults) {
				push(`    ${inlineTable(vault)},`)
			}
			push("]")
		}
		push()
		if (config.vault.uniswapV4) {
			push("# Uniswap V4 positions used for pool-based pricing and on-demand liquidity withdrawal.")
			push("[vault.uniswapV4]")
			if (config.vault.uniswapV4.side !== undefined) {
				push(kv("side", config.vault.uniswapV4.side))
			}
			if (config.vault.uniswapV4.spreadBps !== undefined) {
				push("# Slippage tolerance (bps) for LP redemptions; also the spread around pool mid.")
				push(kv("spreadBps", config.vault.uniswapV4.spreadBps))
			}
			if (config.vault.uniswapV4.positions?.length) {
				push("positions = [")
				for (const position of config.vault.uniswapV4.positions) {
					push(`    ${inlineTable(position)},`)
				}
				push("]")
			}
			push()
		}
	}

	if (config.allowlist) {
		push("# Only orders from these user addresses are processed. Remove the section to accept everyone.")
		push("[allowlist]")
		if (config.allowlist.users) {
			push(kv("users", config.allowlist.users))
		}
		const bySource = config.allowlist.bySource
		if (bySource && Object.keys(bySource).length > 0) {
			push()
			push("[allowlist.bySource]")
			for (const [chain, users] of Object.entries(bySource)) {
				push(kv(chain, users, true))
			}
		}
		push()
	}

	if (config.assets && Object.keys(config.assets).length > 0) {
		push("# Extra assets the built-in registry does not ship (or per-deployment address overrides).")
		for (const [symbol, definition] of Object.entries(config.assets)) {
			push(`[assets.${/^[A-Za-z0-9_-]+$/.test(symbol) ? symbol : JSON.stringify(symbol)}]`)
			for (const [chain, address] of Object.entries(definition)) {
				push(kv(chain, address, true))
			}
			push()
		}
	}

	for (const pair of config.pairs ?? []) {
		emitPair(push, pair)
	}

	emitConfirmationPolicies(push, config.confirmationPolicies)

	config.chains.forEach((chain, index) => {
		const comment = options.chainComments?.[index]
		if (comment) push(`# ${comment}`)
		push("[[chains]]")
		push("# List 2+ organisationally independent RPC providers to enable quorum log scanning.")
		push(kv("rpcUrls", chain.rpcUrls))
		push("# ERC-4337 bundler used to submit fill UserOperations on this chain.")
		push(kv("bundlerUrl", chain.bundlerUrl))
		push()
	})

	return `${out.join("\n").trimEnd()}\n`
}

function emitPair(push: (line?: string) => void, pair: PairConfig): void {
	const sameToken = pair.token0.trim().toUpperCase() === pair.token1.trim().toUpperCase()
	if (sameToken) {
		push(`# Same-asset cross-chain market: ${pair.token0} on one chain for ${pair.token1} on another.`)
		push("# Ask prices are the fraction paid back out — strictly below 1; the gap to par is the spread.")
	} else {
		push(`# Cross-asset market: curves price ${pair.token1} per 1 ${pair.token0}; maxOrderSize caps`)
		push(`# the per-order ${pair.token0} notional. Omit one curve for one-sided LP.`)
	}
	push("[[pairs]]")
	push(kv("token0", pair.token0))
	push(kv("token1", pair.token1))
	if (pair.referenceOnly !== undefined) {
		push("# Price feed only — contributes its rate to USD anchoring but never fills orders.")
		push(kv("referenceOnly", pair.referenceOnly))
	}
	if (pair.maxOrderSize !== undefined) {
		push(kv("maxOrderSize", pair.maxOrderSize))
	}
	if (pair.bidPriceCurve) {
		push(`# ${pair.token1} per ${pair.token0} when the filler *buys* ${pair.token1} from a user.`)
		push("bidPriceCurve = [")
		for (const point of pair.bidPriceCurve) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
	}
	if (pair.askPriceCurve) {
		if (!sameToken) push(`# ${pair.token1} per ${pair.token0} when the filler *sells* ${pair.token1} to a user.`)
		push("askPriceCurve = [")
		for (const point of pair.askPriceCurve) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
	}
	push()
}

function emitConfirmationPolicies(
	push: (line?: string) => void,
	policies: Record<string, ChainConfirmationPolicy> | undefined,
): void {
	if (!policies || Object.keys(policies).length === 0) return
	push("# Block confirmations to wait before filling, by order USD value (reorg protection).")
	push("# Chains not listed here use the built-in defaults.")
	for (const [chainId, policy] of Object.entries(policies)) {
		push(`[confirmationPolicies."${chainId}"]`)
		push("points = [")
		for (const point of policy.points) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
		push()
	}
}

function kv(key: string, value: unknown, quoteKey = false): string {
	const renderedKey = quoteKey || !/^[A-Za-z0-9_-]+$/.test(key) ? JSON.stringify(key) : key
	return `${renderedKey} = ${renderValue(value)}`
}

function renderValue(value: unknown): string {
	if (typeof value === "string") return JSON.stringify(value)
	if (typeof value === "number") {
		if (!Number.isFinite(value)) throw new Error(`Cannot render non-finite number in TOML: ${value}`)
		return String(value)
	}
	if (typeof value === "boolean") return String(value)
	if (Array.isArray(value)) return `[${value.map(renderValue).join(", ")}]`
	if (typeof value === "object" && value !== null) return inlineTable(value)
	throw new Error(`Cannot render value in TOML: ${String(value)}`)
}

function inlineTable(obj: object): string {
	const entries = Object.entries(obj)
		.filter(([, value]) => value !== undefined)
		.map(([key, value]) => kv(key, value))
	return `{ ${entries.join(", ")} }`
}
