import type { FillerTomlConfig, StrategyConfig, ChainConfirmationPolicy } from "@/config/filler-toml"

export interface EmitOptions {
	/** Comment shown above each [[chains]] entry, aligned with config.chains. */
	chainComments?: string[]
}

/**
 * Renders a FillerTomlConfig as a commented TOML document. A generic stringifier
 * can't produce comments or stable section ordering, so the document is emitted
 * section by section; `toml.parse(emitFillerToml(c))` must deep-equal `c`.
 */
export function emitFillerToml(config: FillerTomlConfig, options: EmitOptions = {}): string {
	const out: string[] = []
	const push = (line = "") => out.push(line)

	push("# Simplex filler configuration")
	push("# Generated by `simplex init`. Safe to edit by hand; re-run `simplex init` to update interactively.")
	push()

	push("[simplex]")
	push("# Maximum number of orders processed concurrently. Lower this if your RPCs rate-limit (429s).")
	push(kv("maxConcurrentOrders", config.simplex.maxConcurrentOrders))
	if (config.simplex.logging !== undefined) {
		push("# Log verbosity: trace, debug, info, warn, error")
		push(kv("logging", config.simplex.logging))
	}
	if (config.simplex.watchOnly !== undefined) {
		push("# Watch-only mode: monitor orders without filling. Boolean (global) or per-chain map.")
		push(kv("watchOnly", config.simplex.watchOnly))
	}
	push("# Substrate account (hex seed or mnemonic) that signs bid extrinsics on Hyperbridge.")
	push("# It must hold BRIDGE tokens for fees; fees are claimed back automatically after fills.")
	push(kv("substratePrivateKey", config.simplex.substratePrivateKey))
	push("# Hyperbridge WebSocket endpoint used to submit solver bids.")
	push(kv("hyperbridgeWsUrl", config.simplex.hyperbridgeWsUrl))
	if (config.simplex.entryPointAddress !== undefined) {
		push(kv("entryPointAddress", config.simplex.entryPointAddress))
	}
	if (config.simplex.solverAccountContractAddress !== undefined) {
		push(kv("solverAccountContractAddress", config.simplex.solverAccountContractAddress))
	}
	if (config.simplex.targetGasUnits !== undefined) {
		push("# Gas units to keep deposited at the ERC-4337 EntryPoint on chains without a paymaster.")
		push(kv("targetGasUnits", config.simplex.targetGasUnits))
	}
	push()

	push("# Wallet that signs fills and holds the stablecoin float on every chain.")
	push("# WARNING: contains secrets - keep this file private (chmod 600) and never commit it.")
	push("[simplex.signer]")
	for (const [key, value] of Object.entries(config.simplex.signer ?? {})) {
		if (value !== undefined) push(kv(key, value))
	}
	push()

	if (config.simplex.gasFeeBump) {
		push("# Percentages added on top of the base gasPrice for UserOperations.")
		push("# Higher values win more fill races but cost more gas.")
		push("[simplex.gasFeeBump]")
		for (const [key, value] of Object.entries(config.simplex.gasFeeBump)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	} else {
		push("# Gas fee bump defaults apply: 8% priority fee, 10% max fee on top of base gasPrice.")
		push("# [simplex.gasFeeBump]")
		push("# maxPriorityFeePerGasBumpPercent = 8")
		push("# maxFeePerGasBumpPercent = 10")
		push()
	}

	if (config.simplex.overfillProtection) {
		push("# Bounds per-leg loss when internal pricing is wrong (bug, stale cache, manipulated venue).")
		push("[simplex.overfillProtection]")
		for (const [key, value] of Object.entries(config.simplex.overfillProtection)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	} else {
		push("# Overfill protection defaults apply: output clamped at 5% above the user-requested")
		push("# amount, halt after 3 consecutive clamped orders.")
		push("# [simplex.overfillProtection]")
		push("# maxOverfillBps = 500")
		push("# maxConsecutiveClamps = 3")
		push()
	}

	push("# How often a not-yet-fillable order is re-checked before being dropped.")
	push("[simplex.queue]")
	push(kv("maxRechecks", config.simplex.queue.maxRechecks))
	push(kv("recheckDelayMs", config.simplex.queue.recheckDelayMs))
	push()

	if (config.rebalancing) {
		push("# Rebalancing: triggers when a balance falls to (1 - triggerPercentage) * baseBalance.")
		push("[rebalancing]")
		push(kv("triggerPercentage", config.rebalancing.triggerPercentage))
		push()
		for (const symbol of ["USDC", "USDT"] as const) {
			const balances = config.rebalancing.baseBalances[symbol]
			if (!balances) continue
			push(`[rebalancing.baseBalances.${symbol}]`)
			for (const [chainId, amount] of Object.entries(balances)) {
				push(kv(chainId, amount, true))
			}
			push()
		}
	}

	if (config.binance) {
		push("# Binance CEX rebalancing credentials.")
		push("[binance]")
		for (const [key, value] of Object.entries(config.binance)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	}

	if (config.keeper) {
		push("# SimplexPaymaster fee-recycling keeper (`paymaster-keeper` subcommand).")
		push("[keeper]")
		for (const [key, value] of Object.entries(config.keeper)) {
			if (value !== undefined) push(kv(key, value))
		}
		push()
	}

	if (config.vault) {
		push("# ERC-4626 stablecoin treasury: fills source missing balance from these vaults atomically,")
		push("# and wallet balance above `threshold` is swept back down to `minBalance` to earn yield.")
		push("[vault]")
		if (config.vault.sweepIntervalMs !== undefined) {
			push(kv("sweepIntervalMs", config.vault.sweepIntervalMs))
		}
		push("vaults = [")
		for (const vault of config.vault.vaults) {
			push(`    ${inlineTable(vault)},`)
		}
		push("]")
		push()
	}

	if (config.allowlist) {
		push("# Only orders from these user addresses are processed. Remove the section to accept everyone.")
		push("[allowlist]")
		if (config.allowlist.users) {
			push(kv("users", config.allowlist.users))
		}
		const bySource = config.allowlist.bySource
		if (bySource && Object.keys(bySource).length > 0) {
			push()
			push("[allowlist.bySource]")
			for (const [chain, users] of Object.entries(bySource)) {
				push(kv(chain, users, true))
			}
		}
		push()
	}

	for (const strategy of config.strategies) {
		emitStrategy(push, strategy)
	}

	config.chains.forEach((chain, index) => {
		const comment = options.chainComments?.[index]
		if (comment) push(`# ${comment}`)
		push("[[chains]]")
		push("# List 2+ organisationally independent RPC providers to enable quorum log scanning.")
		push(kv("rpcUrls", chain.rpcUrls))
		push("# ERC-4337 bundler used to submit fill UserOperations on this chain.")
		push(kv("bundlerUrl", chain.bundlerUrl))
		push()
	})

	return `${out.join("\n").trimEnd()}\n`
}

function emitStrategy(push: (line?: string) => void, strategy: StrategyConfig): void {
	if (strategy.type === "stable") {
		push("# Stable strategy: fills same-token cross-chain transfers (USDC->USDC, USDT->USDT).")
		push("[[strategies]]")
		push(kv("type", "stable"))
		push("# Minimum margin (basis points) by order size; points are interpolated into a smooth curve.")
		push("# High bps keeps small orders worthwhile, low bps keeps large orders competitive.")
		push("bpsCurve = [")
		for (const point of strategy.bpsCurve) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
		push()
		emitConfirmationPolicies(push, strategy.confirmationPolicies)
		return
	}

	push("# HyperFX strategy: fills swaps between stablecoins and one exotic token (e.g. cNGN).")
	push("[[strategies]]")
	push(kv("type", "hyperfx"))
	push("# Maximum USD exposure per order; larger orders are partially filled up to this cap.")
	push(kv("maxOrderUsd", strategy.maxOrderUsd))
	if (strategy.spreadBps !== undefined) {
		push("# Spread (basis points) around the Uniswap V4 pool mid when pool pricing is active.")
		push(kv("spreadBps", strategy.spreadBps))
	}
	if (strategy.bidPriceCurve) {
		push("# Exotic tokens per USD when the filler *buys* exotic from a user (exotic -> stable leg).")
		push("bidPriceCurve = [")
		for (const point of strategy.bidPriceCurve) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
	}
	if (strategy.askPriceCurve) {
		push("# Exotic tokens per USD when the filler *sells* exotic to a user (stable -> exotic leg).")
		push("askPriceCurve = [")
		for (const point of strategy.askPriceCurve) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
	}
	push()
	push("# Exotic token contract per chain, keyed by state machine id.")
	push("[strategies.token1]")
	for (const [chain, address] of Object.entries(strategy.token1)) {
		push(kv(chain, address, true))
	}
	push()
	if (strategy.vault?.uniswapV4) {
		push("# Uniswap V4 positions used for pool-based pricing and on-demand liquidity withdrawal.")
		push("[strategies.vault.uniswapV4]")
		if (strategy.vault.uniswapV4.side !== undefined) {
			push(kv("side", strategy.vault.uniswapV4.side))
		}
		if (strategy.vault.uniswapV4.positions) {
			push("positions = [")
			for (const position of strategy.vault.uniswapV4.positions) {
				push(`    ${inlineTable(position)},`)
			}
			push("]")
		}
		push()
	}
	emitConfirmationPolicies(push, strategy.confirmationPolicies)
}

function emitConfirmationPolicies(
	push: (line?: string) => void,
	policies: Record<string, ChainConfirmationPolicy> | undefined,
): void {
	if (!policies) return
	push("# Block confirmations to wait before filling, by order USD value (reorg protection).")
	push("# Chains not listed here use the built-in defaults.")
	for (const [chainId, policy] of Object.entries(policies)) {
		push(`[strategies.confirmationPolicies."${chainId}"]`)
		push("points = [")
		for (const point of policy.points) {
			push(`    ${inlineTable(point)},`)
		}
		push("]")
		push()
	}
}

function kv(key: string, value: unknown, quoteKey = false): string {
	const renderedKey = quoteKey || !/^[A-Za-z0-9_-]+$/.test(key) ? JSON.stringify(key) : key
	return `${renderedKey} = ${renderValue(value)}`
}

function renderValue(value: unknown): string {
	if (typeof value === "string") return JSON.stringify(value)
	if (typeof value === "number") {
		if (!Number.isFinite(value)) throw new Error(`Cannot render non-finite number in TOML: ${value}`)
		return String(value)
	}
	if (typeof value === "boolean") return String(value)
	if (Array.isArray(value)) return `[${value.map(renderValue).join(", ")}]`
	if (typeof value === "object" && value !== null) return inlineTable(value)
	throw new Error(`Cannot render value in TOML: ${String(value)}`)
}

function inlineTable(obj: object): string {
	const entries = Object.entries(obj)
		.filter(([, value]) => value !== undefined)
		.map(([key, value]) => kv(key, value))
	return `{ ${entries.join(", ")} }`
}
