// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.30;

import {Test, console} from "forge-std/Test.sol";
import {IntermediateState} from "@hyperbridge/core/interfaces/IConsensusV2.sol";

import {BlsBeefy} from "../../src/consensus/BlsBeefy.sol";
import {BeefyConsensusState} from "../../src/consensus/Types.sol";
import {ApkProof} from "./vendor/ApkProof.sol";
import {PlonkVerifier} from "./vendor/PlonkVerifier.sol";

/**
 * @title BEEFY verified through an aggregate public key proof.
 *
 * @notice The fixtures come from `bls_apk_live_inputs` and `bls_apk_live_fixture` in the Rust
 * verifier, plus a PLONK proof generated by gnark-apk-proofs for the same validator set. Every
 * part is real: the commitment was signed by a running relay's paired ecdsa_bls381 validators, the
 * MMR proof has actual depth, and the parachain header is a registered para's.
 *
 * The point of this test is the gas number, and it is only comparable to `BlsBeefyTest`'s
 * `test_verify_live_proof` because both run the whole client over live data in the same harness.
 *
 * Needs EIP-2537:
 *   FOUNDRY_PROFILE=bls forge test --match-contract BlsBeefyTest -vv --gas-report
 */
contract BlsBeefyTest is Test {
    BlsBeefy internal client;

    function setUp() public {
        // False selects the basic ciphersuite, which is what substrate's BEEFY signs with. PoP
        // would hash the same message to a different point and fail with nothing to explain why.
        ApkProof apk = new ApkProof(address(new PlonkVerifier()));
        // The fixture's proof carries para 4009's header, which is where its digest comes from.
        client = new BlsBeefy(address(apk), 4009);
    }

    function _state() internal view returns (bytes memory) {
        return vm.parseBytes(vm.readFile("tests/foundry/fixtures/bls-apk-beefy-state.hex"));
    }

    function _proof() internal view returns (bytes memory) {
        return vm.parseBytes(vm.readFile("tests/foundry/fixtures/bls-apk-beefy-proof.hex"));
    }

    /// A complete consensus update: SNARK over the aggregate key, the batched pairing that binds
    /// apk2 and checks the signature, MMR leaf inclusion, and the parachain header proof.
    function test_verify_live_proof() public view {
        (bytes memory newStateBytes, IntermediateState[] memory intermediates,) = client.verify(_state(), _proof());

        BeefyConsensusState memory newState = abi.decode(newStateBytes, (BeefyConsensusState));
        BeefyConsensusState memory oldState = abi.decode(_state(), (BeefyConsensusState));

        assertGt(newState.latestHeight, oldState.latestHeight, "height should advance");
        assertEq(intermediates.length, 1, "should finalize the registered parachain");
        assertEq(intermediates[0].stateMachineId, 4009, "should be para 4009");
        assertGt(intermediates[0].height, 0, "parachain height should be non-zero");
    }

    /// Isolates the cost of the update itself, so the number can be compared with the merkle
    /// client's without the calldata and fixture reading counted in.
    function test_gas_verify_live_proof() public view {
        bytes memory state = _state();
        bytes memory proof = _proof();

        uint256 before = gasleft();
        client.verify(state, proof);
        uint256 used = before - gasleft();

        console.log("BlsBeefy.verify gas:", used);
    }

    /// Replaying a proof the state has already passed is a no-op rather than a revert, matching the
    /// merkle client.
    function test_stale_proof_is_a_noop() public view {
        (bytes memory advanced,,) = client.verify(_state(), _proof());

        (bytes memory again, IntermediateState[] memory intermediates,) = client.verify(advanced, _proof());

        assertEq(again, advanced, "state should be unchanged");
        assertEq(intermediates.length, 0, "a stale proof finalizes nothing");
    }
}
