// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

import {IntermediateState} from "@hyperbridge/core/interfaces/IConsensus.sol";

import {SP1Beefy} from "../../src/consensus/SP1Beefy.sol";
import {BeefyConsensusState} from "../../src/consensus/Types.sol";

/// @notice Verifies an SP1Beefy proof generated by tesseract-prover (zk-beefy)
/// against the production SP1Beefy contract deployed on ethereum mainnet.
///
contract SP1BeefyForkTest is Test {
    /// SP1Beefy deployed by DeployHostUpdates.s.sol — same CREATE2 address on all chains.
    address internal constant SP1_BEEFY = 0x82582f85cf370adCB61D97dab3068c0C4102Ccb6;

    /// Fixture committed under tests/foundry/fixtures/. Regenerate with the zk-beefy test:
    ///   cargo test --release -p zk-beefy --lib tests::test_sp1_beefy -- --ignored --nocapture
    /// (See FIXTURE_OUT env var in tesseract/consensus/beefy/zk/src/tests.rs.)
    string internal constant FIXTURE_PATH = "tests/foundry/fixtures/sp1_beefy_fixture.json";
    uint256 internal mainnetFork;

    function setUp() public {
        string memory fork_url = vm.envString("MAINNET_FORK_URL");

        // mainnet fork creation
        mainnetFork = vm.createFork(fork_url);

        // mainnet fork selection
        vm.selectFork(mainnetFork);   
    }

    function testVerifyMainnetProof() public view {
        string memory json = vm.readFile(FIXTURE_PATH);

        bytes memory previousState = vm.parseJsonBytes(json, ".previous_state");
        bytes memory proof = vm.parseJsonBytes(json, ".proof");
        uint256 blockNumber = vm.parseJsonUint(json, ".block_number");

        console.log("Fixture block_number:", blockNumber);
        console.log("previousState bytes:", previousState.length);
        console.log("proof bytes:", proof.length);

        BeefyConsensusState memory prev = abi.decode(previousState, (BeefyConsensusState));
        console.log("prev.latestHeight:", prev.latestHeight);
        console.log("prev.currentAuthoritySet.id:", prev.currentAuthoritySet.id);

        (bytes memory newStateEnc, IntermediateState[] memory intermediates, uint256 nextAuthId) =
            SP1Beefy(SP1_BEEFY).verify(previousState, proof);

        BeefyConsensusState memory newState = abi.decode(newStateEnc, (BeefyConsensusState));
        console.log("new.latestHeight:", newState.latestHeight);
        console.log("intermediates.length:", intermediates.length);
        console.log("nextAuthoritySetId:", nextAuthId);

        assertGt(newState.latestHeight, prev.latestHeight, "latestHeight must advance");
        assertEq(newState.latestHeight, blockNumber, "latestHeight must equal commitment block");

        // Cross-check every intermediate against expectations derived by the prover from
        // the same parachain header digests (ISMP ConsensusDigest + AURA preruntime).
        require(intermediates.length > 0, "verify returned no intermediates");

        for (uint256 i = 0; i < intermediates.length; i++) {
            string memory base = string.concat(".intermediates_expected[", vm.toString(i), "]");
            uint256 expStateMachineId = vm.parseJsonUint(json, string.concat(base, ".state_machine_id"));
            uint256 expHeight = vm.parseJsonUint(json, string.concat(base, ".height"));
            uint256 expTimestamp = vm.parseJsonUint(json, string.concat(base, ".timestamp"));
            bytes32 expOverlay = vm.parseJsonBytes32(json, string.concat(base, ".overlay_root"));
            bytes32 expState = vm.parseJsonBytes32(json, string.concat(base, ".state_root"));

            console.log("intermediate", i, "stateMachineId:", intermediates[i].stateMachineId);
            console.log("intermediate", i, "height:", intermediates[i].height);
            console.log("intermediate", i, "timestamp:", intermediates[i].commitment.timestamp);

            assertEq(intermediates[i].stateMachineId, expStateMachineId, "stateMachineId mismatch");
            assertEq(intermediates[i].height, expHeight, "height mismatch");
            assertEq(intermediates[i].commitment.timestamp, expTimestamp, "timestamp mismatch");
            assertEq(intermediates[i].commitment.overlayRoot, expOverlay, "overlayRoot mismatch");
            assertEq(intermediates[i].commitment.stateRoot, expState, "stateRoot mismatch");
        }
    }
}
