name: Tesseract Feature Tag Docker Publish

on:
    push:
        tags:
            - "tesseract-consensus-[a-z]+"

concurrency:
    group: release-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_and_publish:
        runs-on: release-runner
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  submodules: recursive

            - uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: "${{ secrets.SSH_KEY }}"

            - name: Install toolchain
              uses: dtolnay/rust-toolchain@nightly
              with:
                  toolchain: stable

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache-dependency-path: "evm/pnpm-lock.yaml"
                  cache: "pnpm"

            - name: Install npm dependencies
              working-directory: evm
              run: |
                  pnpm install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Build Foundry artifacts
              working-directory: evm
              run: forge build

            - name: Build
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y clang netcat wget curl libssl-dev llvm libudev-dev make protobuf-compiler pkg-config
                  feature_flag=$(echo "$GITHUB_REF_NAME" | cut -d'-' -f"3")
                  cargo build --release -p tesseract-consensus --features $feature_flag
            - name: Install Cargo get
              run: cargo install cargo-get

            - name: Resolve feature flag
              id: feature
              run: |
                  FEATURE=$(echo "$GITHUB_REF_NAME" | cut -d'-' -f"3")
                  echo "flag=${FEATURE}" >> "$GITHUB_OUTPUT"

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./scripts/docker/consensus.Dockerfile
                  push: true
                  tags: |
                      polytopelabs/tesseract-consensus:${{ steps.feature.outputs.flag }}
                      ghcr.io/${{ github.repository_owner }}/tesseract-consensus:${{ steps.feature.outputs.flag }}
